/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Cdr API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type {
	ApiErrorResponse,
	CallRecordDetailResponse,
	CallRecordListFilter,
	CallRecordResponse,
	CallRecordResponsePagedResult,
	CreateCallRecordRequest,
	UpdateCallRecordRequest,
} from "../../models";

import { customFetch } from "../../../custom-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Lista rekordów CDR
 */
export type getCallRecordsListResponse200 = {
	data: CallRecordResponsePagedResult;
	status: 200;
};

export type getCallRecordsListResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type getCallRecordsListResponseSuccess =
	getCallRecordsListResponse200 & {
		headers: Headers;
	};
export type getCallRecordsListResponseError = getCallRecordsListResponse400 & {
	headers: Headers;
};

export type getCallRecordsListResponse =
	| getCallRecordsListResponseSuccess
	| getCallRecordsListResponseError;

export const getGetCallRecordsListUrl = () => {
	return `/api/cdr/call-records/list`;
};

export const getCallRecordsList = async (
	callRecordListFilter: CallRecordListFilter,
	options?: RequestInit,
): Promise<getCallRecordsListResponse> => {
	return customFetch<getCallRecordsListResponse>(getGetCallRecordsListUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(callRecordListFilter),
	});
};

export const getGetCallRecordsListMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getCallRecordsList>>,
		TError,
		{ data: CallRecordListFilter },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getCallRecordsList>>,
	TError,
	{ data: CallRecordListFilter },
	TContext
> => {
	const mutationKey = ["getCallRecordsList"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getCallRecordsList>>,
		{ data: CallRecordListFilter }
	> = (props) => {
		const { data } = props ?? {};

		return getCallRecordsList(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetCallRecordsListMutationResult = NonNullable<
	Awaited<ReturnType<typeof getCallRecordsList>>
>;
export type GetCallRecordsListMutationBody = CallRecordListFilter;
export type GetCallRecordsListMutationError = ApiErrorResponse;

/**
 * @summary Lista rekordów CDR
 */
export const useGetCallRecordsList = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getCallRecordsList>>,
			TError,
			{ data: CallRecordListFilter },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getCallRecordsList>>,
	TError,
	{ data: CallRecordListFilter },
	TContext
> => {
	const mutationOptions = getGetCallRecordsListMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Pobierz rekord CDR
 */
export type getCallRecordByGidResponse200 = {
	data: CallRecordDetailResponse;
	status: 200;
};

export type getCallRecordByGidResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type getCallRecordByGidResponseSuccess =
	getCallRecordByGidResponse200 & {
		headers: Headers;
	};
export type getCallRecordByGidResponseError = getCallRecordByGidResponse404 & {
	headers: Headers;
};

export type getCallRecordByGidResponse =
	| getCallRecordByGidResponseSuccess
	| getCallRecordByGidResponseError;

export const getGetCallRecordByGidUrl = (gid: string) => {
	return `/api/cdr/call-records/${gid}`;
};

export const getCallRecordByGid = async (
	gid: string,
	options?: RequestInit,
): Promise<getCallRecordByGidResponse> => {
	return customFetch<getCallRecordByGidResponse>(
		getGetCallRecordByGidUrl(gid),
		{
			...options,
			method: "GET",
		},
	);
};

export const getGetCallRecordByGidQueryKey = (gid?: string) => {
	return [`/api/cdr/call-records/${gid}`] as const;
};

export const getGetCallRecordByGidQueryOptions = <
	TData = Awaited<ReturnType<typeof getCallRecordByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCallRecordByGid>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetCallRecordByGidQueryKey(gid);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getCallRecordByGid>>
	> = ({ signal }) => getCallRecordByGid(gid, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!gid,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getCallRecordByGid>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCallRecordByGidQueryResult = NonNullable<
	Awaited<ReturnType<typeof getCallRecordByGid>>
>;
export type GetCallRecordByGidQueryError = ApiErrorResponse;

export function useGetCallRecordByGid<
	TData = Awaited<ReturnType<typeof getCallRecordByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCallRecordByGid>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getCallRecordByGid>>,
					TError,
					Awaited<ReturnType<typeof getCallRecordByGid>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCallRecordByGid<
	TData = Awaited<ReturnType<typeof getCallRecordByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCallRecordByGid>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getCallRecordByGid>>,
					TError,
					Awaited<ReturnType<typeof getCallRecordByGid>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCallRecordByGid<
	TData = Awaited<ReturnType<typeof getCallRecordByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCallRecordByGid>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Pobierz rekord CDR
 */

export function useGetCallRecordByGid<
	TData = Awaited<ReturnType<typeof getCallRecordByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCallRecordByGid>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetCallRecordByGidQueryOptions(gid, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * @summary Aktualizuj rekord CDR
 */
export type updateCallRecordResponse200 = {
	data: CallRecordResponse;
	status: 200;
};

export type updateCallRecordResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type updateCallRecordResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type updateCallRecordResponseSuccess = updateCallRecordResponse200 & {
	headers: Headers;
};
export type updateCallRecordResponseError = (
	| updateCallRecordResponse400
	| updateCallRecordResponse404
) & {
	headers: Headers;
};

export type updateCallRecordResponse =
	| updateCallRecordResponseSuccess
	| updateCallRecordResponseError;

export const getUpdateCallRecordUrl = (gid: string) => {
	return `/api/cdr/call-records/${gid}`;
};

export const updateCallRecord = async (
	gid: string,
	updateCallRecordRequest: UpdateCallRecordRequest,
	options?: RequestInit,
): Promise<updateCallRecordResponse> => {
	return customFetch<updateCallRecordResponse>(getUpdateCallRecordUrl(gid), {
		...options,
		method: "PUT",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(updateCallRecordRequest),
	});
};

export const getUpdateCallRecordMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateCallRecord>>,
		TError,
		{ gid: string; data: UpdateCallRecordRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateCallRecord>>,
	TError,
	{ gid: string; data: UpdateCallRecordRequest },
	TContext
> => {
	const mutationKey = ["updateCallRecord"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateCallRecord>>,
		{ gid: string; data: UpdateCallRecordRequest }
	> = (props) => {
		const { gid, data } = props ?? {};

		return updateCallRecord(gid, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateCallRecordMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateCallRecord>>
>;
export type UpdateCallRecordMutationBody = UpdateCallRecordRequest;
export type UpdateCallRecordMutationError = ApiErrorResponse;

/**
 * @summary Aktualizuj rekord CDR
 */
export const useUpdateCallRecord = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateCallRecord>>,
			TError,
			{ gid: string; data: UpdateCallRecordRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateCallRecord>>,
	TError,
	{ gid: string; data: UpdateCallRecordRequest },
	TContext
> => {
	const mutationOptions = getUpdateCallRecordMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Usuń rekord CDR
 */
export type deleteCallRecordResponse200 = {
	data: boolean;
	status: 200;
};

export type deleteCallRecordResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type deleteCallRecordResponseSuccess = deleteCallRecordResponse200 & {
	headers: Headers;
};
export type deleteCallRecordResponseError = deleteCallRecordResponse404 & {
	headers: Headers;
};

export type deleteCallRecordResponse =
	| deleteCallRecordResponseSuccess
	| deleteCallRecordResponseError;

export const getDeleteCallRecordUrl = (gid: string) => {
	return `/api/cdr/call-records/${gid}`;
};

export const deleteCallRecord = async (
	gid: string,
	options?: RequestInit,
): Promise<deleteCallRecordResponse> => {
	return customFetch<deleteCallRecordResponse>(getDeleteCallRecordUrl(gid), {
		...options,
		method: "DELETE",
	});
};

export const getDeleteCallRecordMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteCallRecord>>,
		TError,
		{ gid: string },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteCallRecord>>,
	TError,
	{ gid: string },
	TContext
> => {
	const mutationKey = ["deleteCallRecord"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteCallRecord>>,
		{ gid: string }
	> = (props) => {
		const { gid } = props ?? {};

		return deleteCallRecord(gid, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteCallRecordMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteCallRecord>>
>;

export type DeleteCallRecordMutationError = ApiErrorResponse;

/**
 * @summary Usuń rekord CDR
 */
export const useDeleteCallRecord = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteCallRecord>>,
			TError,
			{ gid: string },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteCallRecord>>,
	TError,
	{ gid: string },
	TContext
> => {
	const mutationOptions = getDeleteCallRecordMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Utwórz rekord CDR
 */
export type createCallRecordResponse200 = {
	data: CallRecordResponse;
	status: 200;
};

export type createCallRecordResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type createCallRecordResponseSuccess = createCallRecordResponse200 & {
	headers: Headers;
};
export type createCallRecordResponseError = createCallRecordResponse400 & {
	headers: Headers;
};

export type createCallRecordResponse =
	| createCallRecordResponseSuccess
	| createCallRecordResponseError;

export const getCreateCallRecordUrl = () => {
	return `/api/cdr/call-records`;
};

export const createCallRecord = async (
	createCallRecordRequest: CreateCallRecordRequest,
	options?: RequestInit,
): Promise<createCallRecordResponse> => {
	return customFetch<createCallRecordResponse>(getCreateCallRecordUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(createCallRecordRequest),
	});
};

export const getCreateCallRecordMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createCallRecord>>,
		TError,
		{ data: CreateCallRecordRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createCallRecord>>,
	TError,
	{ data: CreateCallRecordRequest },
	TContext
> => {
	const mutationKey = ["createCallRecord"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createCallRecord>>,
		{ data: CreateCallRecordRequest }
	> = (props) => {
		const { data } = props ?? {};

		return createCallRecord(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateCallRecordMutationResult = NonNullable<
	Awaited<ReturnType<typeof createCallRecord>>
>;
export type CreateCallRecordMutationBody = CreateCallRecordRequest;
export type CreateCallRecordMutationError = ApiErrorResponse;

/**
 * @summary Utwórz rekord CDR
 */
export const useCreateCallRecord = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createCallRecord>>,
			TError,
			{ data: CreateCallRecordRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createCallRecord>>,
	TError,
	{ data: CreateCallRecordRequest },
	TContext
> => {
	const mutationOptions = getCreateCallRecordMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
