/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX DataSource API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface DataSourceTypeInfo {
	value?: number;
	/** @nullable */
	name?: string | null;
}
