/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX DataSource API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export type DataSourceType =
	(typeof DataSourceType)[keyof typeof DataSourceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DataSourceType = {
	Countries: "Countries",
	Provinces: "Provinces",
	UsersSales: "UsersSales",
	UsersAll: "UsersAll",
	Clients: "Clients",
	Sbu: "Sbu",
	Teams: "Teams",
	Benefits: "Benefits",
	Certificates: "Certificates",
	Tools: "Tools",
	Traits: "Traits",
	Occupations: "Occupations",
	Positions: "Positions",
} as const;
