/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX DataSource API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { PickerDataItem } from "./pickerDataItem";

export interface PickerDataResponse {
	/** @nullable */
	items?: PickerDataItem[] | null;
	totalCount?: number;
}
