/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX DataSource API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { DataSourceType } from "./dataSourceType";

export interface ResolveRequest {
	dataSourceType?: DataSourceType;
	/** @nullable */
	gids?: string[] | null;
	/** @nullable */
	ids?: number[] | null;
}
