/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX DataSource API (via Gateway)
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type SearchRequestFilters = { [key: string]: string } | null;
