/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX DataSource API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { DataSourceType } from "./dataSourceType";
import type { SearchRequestFilters } from "./searchRequestFilters";
import type { SearchRequestContextFilters } from "./searchRequestContextFilters";

export interface SearchRequest {
	dataSourceType?: DataSourceType;
	/** @nullable */
	query?: string | null;
	limit?: number;
	/** @nullable */
	filters?: SearchRequestFilters;
	/** @nullable */
	contextFilters?: SearchRequestContextFilters;
}
