/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX DataSource API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { DataSourceType } from "./dataSourceType";
import type { SuggestionsRequestContextFilters } from "./suggestionsRequestContextFilters";

export interface SuggestionsRequest {
	dataSourceType?: DataSourceType;
	limit?: number;
	/** @nullable */
	contextFilters?: SuggestionsRequestContextFilters;
}
