/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rate API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type {
	ApiErrorResponse,
	CreateRateRequest,
	LookupRateParams,
	RateListFilter,
	RateResponse,
	RateResponsePagedResult,
	UpdateRateRequest,
} from "../../models";

import { customFetch } from "../../../custom-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Lista stawek
 */
export type getRatesListResponse200 = {
	data: RateResponsePagedResult;
	status: 200;
};

export type getRatesListResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type getRatesListResponseSuccess = getRatesListResponse200 & {
	headers: Headers;
};
export type getRatesListResponseError = getRatesListResponse400 & {
	headers: Headers;
};

export type getRatesListResponse =
	| getRatesListResponseSuccess
	| getRatesListResponseError;

export const getGetRatesListUrl = () => {
	return `/api/rate/rates/list`;
};

export const getRatesList = async (
	rateListFilter: RateListFilter,
	options?: RequestInit,
): Promise<getRatesListResponse> => {
	return customFetch<getRatesListResponse>(getGetRatesListUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(rateListFilter),
	});
};

export const getGetRatesListMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getRatesList>>,
		TError,
		{ data: RateListFilter },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getRatesList>>,
	TError,
	{ data: RateListFilter },
	TContext
> => {
	const mutationKey = ["getRatesList"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getRatesList>>,
		{ data: RateListFilter }
	> = (props) => {
		const { data } = props ?? {};

		return getRatesList(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetRatesListMutationResult = NonNullable<
	Awaited<ReturnType<typeof getRatesList>>
>;
export type GetRatesListMutationBody = RateListFilter;
export type GetRatesListMutationError = ApiErrorResponse;

/**
 * @summary Lista stawek
 */
export const useGetRatesList = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getRatesList>>,
			TError,
			{ data: RateListFilter },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getRatesList>>,
	TError,
	{ data: RateListFilter },
	TContext
> => {
	const mutationOptions = getGetRatesListMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Pobierz stawkę
 */
export type getRateByGidResponse200 = {
	data: RateResponse;
	status: 200;
};

export type getRateByGidResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type getRateByGidResponseSuccess = getRateByGidResponse200 & {
	headers: Headers;
};
export type getRateByGidResponseError = getRateByGidResponse404 & {
	headers: Headers;
};

export type getRateByGidResponse =
	| getRateByGidResponseSuccess
	| getRateByGidResponseError;

export const getGetRateByGidUrl = (gid: string) => {
	return `/api/rate/rates/${gid}`;
};

export const getRateByGid = async (
	gid: string,
	options?: RequestInit,
): Promise<getRateByGidResponse> => {
	return customFetch<getRateByGidResponse>(getGetRateByGidUrl(gid), {
		...options,
		method: "GET",
	});
};

export const getGetRateByGidQueryKey = (gid?: string) => {
	return [`/api/rate/rates/${gid}`] as const;
};

export const getGetRateByGidQueryOptions = <
	TData = Awaited<ReturnType<typeof getRateByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getRateByGid>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetRateByGidQueryKey(gid);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getRateByGid>>> = ({
		signal,
	}) => getRateByGid(gid, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!gid,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getRateByGid>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRateByGidQueryResult = NonNullable<
	Awaited<ReturnType<typeof getRateByGid>>
>;
export type GetRateByGidQueryError = ApiErrorResponse;

export function useGetRateByGid<
	TData = Awaited<ReturnType<typeof getRateByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getRateByGid>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getRateByGid>>,
					TError,
					Awaited<ReturnType<typeof getRateByGid>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRateByGid<
	TData = Awaited<ReturnType<typeof getRateByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getRateByGid>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getRateByGid>>,
					TError,
					Awaited<ReturnType<typeof getRateByGid>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRateByGid<
	TData = Awaited<ReturnType<typeof getRateByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getRateByGid>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Pobierz stawkę
 */

export function useGetRateByGid<
	TData = Awaited<ReturnType<typeof getRateByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getRateByGid>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetRateByGidQueryOptions(gid, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * @summary Aktualizuj stawkę
 */
export type updateRateResponse200 = {
	data: RateResponse;
	status: 200;
};

export type updateRateResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type updateRateResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type updateRateResponseSuccess = updateRateResponse200 & {
	headers: Headers;
};
export type updateRateResponseError = (
	| updateRateResponse400
	| updateRateResponse404
) & {
	headers: Headers;
};

export type updateRateResponse =
	| updateRateResponseSuccess
	| updateRateResponseError;

export const getUpdateRateUrl = (gid: string) => {
	return `/api/rate/rates/${gid}`;
};

export const updateRate = async (
	gid: string,
	updateRateRequest: UpdateRateRequest,
	options?: RequestInit,
): Promise<updateRateResponse> => {
	return customFetch<updateRateResponse>(getUpdateRateUrl(gid), {
		...options,
		method: "PUT",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(updateRateRequest),
	});
};

export const getUpdateRateMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateRate>>,
		TError,
		{ gid: string; data: UpdateRateRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateRate>>,
	TError,
	{ gid: string; data: UpdateRateRequest },
	TContext
> => {
	const mutationKey = ["updateRate"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateRate>>,
		{ gid: string; data: UpdateRateRequest }
	> = (props) => {
		const { gid, data } = props ?? {};

		return updateRate(gid, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateRateMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateRate>>
>;
export type UpdateRateMutationBody = UpdateRateRequest;
export type UpdateRateMutationError = ApiErrorResponse;

/**
 * @summary Aktualizuj stawkę
 */
export const useUpdateRate = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateRate>>,
			TError,
			{ gid: string; data: UpdateRateRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateRate>>,
	TError,
	{ gid: string; data: UpdateRateRequest },
	TContext
> => {
	const mutationOptions = getUpdateRateMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Usuń stawkę
 */
export type deleteRateResponse200 = {
	data: boolean;
	status: 200;
};

export type deleteRateResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type deleteRateResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type deleteRateResponseSuccess = deleteRateResponse200 & {
	headers: Headers;
};
export type deleteRateResponseError = (
	| deleteRateResponse400
	| deleteRateResponse404
) & {
	headers: Headers;
};

export type deleteRateResponse =
	| deleteRateResponseSuccess
	| deleteRateResponseError;

export const getDeleteRateUrl = (gid: string) => {
	return `/api/rate/rates/${gid}`;
};

export const deleteRate = async (
	gid: string,
	options?: RequestInit,
): Promise<deleteRateResponse> => {
	return customFetch<deleteRateResponse>(getDeleteRateUrl(gid), {
		...options,
		method: "DELETE",
	});
};

export const getDeleteRateMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteRate>>,
		TError,
		{ gid: string },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteRate>>,
	TError,
	{ gid: string },
	TContext
> => {
	const mutationKey = ["deleteRate"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteRate>>,
		{ gid: string }
	> = (props) => {
		const { gid } = props ?? {};

		return deleteRate(gid, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteRateMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteRate>>
>;

export type DeleteRateMutationError = ApiErrorResponse;

/**
 * @summary Usuń stawkę
 */
export const useDeleteRate = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteRate>>,
			TError,
			{ gid: string },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteRate>>,
	TError,
	{ gid: string },
	TContext
> => {
	const mutationOptions = getDeleteRateMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Utwórz stawkę
 */
export type createRateResponse200 = {
	data: RateResponse;
	status: 200;
};

export type createRateResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type createRateResponseSuccess = createRateResponse200 & {
	headers: Headers;
};
export type createRateResponseError = createRateResponse400 & {
	headers: Headers;
};

export type createRateResponse =
	| createRateResponseSuccess
	| createRateResponseError;

export const getCreateRateUrl = () => {
	return `/api/rate/rates`;
};

export const createRate = async (
	createRateRequest: CreateRateRequest,
	options?: RequestInit,
): Promise<createRateResponse> => {
	return customFetch<createRateResponse>(getCreateRateUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(createRateRequest),
	});
};

export const getCreateRateMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createRate>>,
		TError,
		{ data: CreateRateRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createRate>>,
	TError,
	{ data: CreateRateRequest },
	TContext
> => {
	const mutationKey = ["createRate"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createRate>>,
		{ data: CreateRateRequest }
	> = (props) => {
		const { data } = props ?? {};

		return createRate(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateRateMutationResult = NonNullable<
	Awaited<ReturnType<typeof createRate>>
>;
export type CreateRateMutationBody = CreateRateRequest;
export type CreateRateMutationError = ApiErrorResponse;

/**
 * @summary Utwórz stawkę
 */
export const useCreateRate = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createRate>>,
			TError,
			{ data: CreateRateRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createRate>>,
	TError,
	{ data: CreateRateRequest },
	TContext
> => {
	const mutationOptions = getCreateRateMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Znajdź stawkę dla numeru
 */
export type lookupRateResponse200 = {
	data: RateResponse;
	status: 200;
};

export type lookupRateResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type lookupRateResponseSuccess = lookupRateResponse200 & {
	headers: Headers;
};
export type lookupRateResponseError = lookupRateResponse404 & {
	headers: Headers;
};

export type lookupRateResponse =
	| lookupRateResponseSuccess
	| lookupRateResponseError;

export const getLookupRateUrl = (params: LookupRateParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/api/rate/rates/lookup?${stringifiedParams}`
		: `/api/rate/rates/lookup`;
};

export const lookupRate = async (
	params: LookupRateParams,
	options?: RequestInit,
): Promise<lookupRateResponse> => {
	return customFetch<lookupRateResponse>(getLookupRateUrl(params), {
		...options,
		method: "GET",
	});
};

export const getLookupRateQueryKey = (params?: LookupRateParams) => {
	return [`/api/rate/rates/lookup`, ...(params ? [params] : [])] as const;
};

export const getLookupRateQueryOptions = <
	TData = Awaited<ReturnType<typeof lookupRate>>,
	TError = ApiErrorResponse,
>(
	params: LookupRateParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof lookupRate>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getLookupRateQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof lookupRate>>> = ({
		signal,
	}) => lookupRate(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof lookupRate>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LookupRateQueryResult = NonNullable<
	Awaited<ReturnType<typeof lookupRate>>
>;
export type LookupRateQueryError = ApiErrorResponse;

export function useLookupRate<
	TData = Awaited<ReturnType<typeof lookupRate>>,
	TError = ApiErrorResponse,
>(
	params: LookupRateParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof lookupRate>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof lookupRate>>,
					TError,
					Awaited<ReturnType<typeof lookupRate>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLookupRate<
	TData = Awaited<ReturnType<typeof lookupRate>>,
	TError = ApiErrorResponse,
>(
	params: LookupRateParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof lookupRate>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof lookupRate>>,
					TError,
					Awaited<ReturnType<typeof lookupRate>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLookupRate<
	TData = Awaited<ReturnType<typeof lookupRate>>,
	TError = ApiErrorResponse,
>(
	params: LookupRateParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof lookupRate>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Znajdź stawkę dla numeru
 */

export function useLookupRate<
	TData = Awaited<ReturnType<typeof lookupRate>>,
	TError = ApiErrorResponse,
>(
	params: LookupRateParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof lookupRate>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getLookupRateQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}
