/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Fincosts API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface ApiErrorResponse {
	/** @nullable */
	code?: string | null;
	/** @nullable */
	message?: string | null;
	/** @nullable */
	validationErrors?: string[] | null;
}
