/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Fincosts API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { DocumentEntryResponse } from "./documentEntryResponse";

export interface DocumentEntryResponsePagedResult {
	/** @nullable */
	items?: DocumentEntryResponse[] | null;
	totalCount?: number;
	pageNumber?: number;
	pageSize?: number;
	readonly totalPages?: number;
	readonly hasPreviousPage?: boolean;
	readonly hasNextPage?: boolean;
}
