/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Fincosts API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface VatRateTypeResponse {
	id?: number;
	/** @nullable */
	namePL?: string | null;
	/** @nullable */
	nameEN?: string | null;
	vatRate?: number;
}
