// <auto-generated />
using System;
using DataSource.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataSource.Data.Migrations
{
    [DbContext(typeof(DataSourceDbContext))]
    partial class DataSourceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DataSource.Data.Entities.VwBenefit", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubLabel")
                        .HasColumnType("longtext");

                    b.HasKey("RecordId");

                    b.ToTable((string)null);

                    b.ToView("vw_benefits", (string)null);
                });

            modelBuilder.Entity("DataSource.Data.Entities.VwCertificate", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubLabel")
                        .HasColumnType("longtext");

                    b.HasKey("RecordId");

                    b.ToTable((string)null);

                    b.ToView("vw_certificates", (string)null);
                });

            modelBuilder.Entity("DataSource.Data.Entities.VwClient", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SubLabel")
                        .HasColumnType("longtext");

                    b.HasKey("RecordId");

                    b.ToTable((string)null);

                    b.ToView("vw_clients", (string)null);
                });

            modelBuilder.Entity("DataSource.Data.Entities.VwCountry", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubLabel")
                        .HasColumnType("longtext");

                    b.HasKey("RecordId");

                    b.ToTable((string)null);

                    b.ToView("vw_countries", (string)null);
                });

            modelBuilder.Entity("DataSource.Data.Entities.VwOccupation", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSelectable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("SubLabel")
                        .HasColumnType("longtext");

                    b.HasKey("RecordId");

                    b.ToTable((string)null);

                    b.ToView("vw_occupation_codes", (string)null);
                });

            modelBuilder.Entity("DataSource.Data.Entities.VwPosition", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubLabel")
                        .HasColumnType("longtext");

                    b.HasKey("RecordId");

                    b.ToTable((string)null);

                    b.ToView("vw_positions", (string)null);
                });

            modelBuilder.Entity("DataSource.Data.Entities.VwProvince", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubLabel")
                        .HasColumnType("longtext");

                    b.HasKey("RecordId");

                    b.ToTable((string)null);

                    b.ToView("vw_provinces", (string)null);
                });

            modelBuilder.Entity("DataSource.Data.Entities.VwSbu", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<string>("SubLabel")
                        .HasColumnType("longtext");

                    b.HasKey("RecordId");

                    b.ToTable((string)null);

                    b.ToView("vw_sbu", (string)null);
                });

            modelBuilder.Entity("DataSource.Data.Entities.VwTeam", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SbuGid")
                        .HasColumnType("longtext");

                    b.Property<string>("SubLabel")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("RecordId");

                    b.ToTable((string)null);

                    b.ToView("vw_teams", (string)null);
                });

            modelBuilder.Entity("DataSource.Data.Entities.VwTool", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubLabel")
                        .HasColumnType("longtext");

                    b.HasKey("RecordId");

                    b.ToTable((string)null);

                    b.ToView("vw_tools", (string)null);
                });

            modelBuilder.Entity("DataSource.Data.Entities.VwTrait", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubLabel")
                        .HasColumnType("longtext");

                    b.HasKey("RecordId");

                    b.ToTable((string)null);

                    b.ToView("vw_traits", (string)null);
                });

            modelBuilder.Entity("DataSource.Data.Entities.VwUserSales", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubLabel")
                        .HasColumnType("longtext");

                    b.HasKey("RecordId");

                    b.ToTable((string)null);

                    b.ToView("vw_users_sales", (string)null);
                });

            modelBuilder.Entity("DataSource.Data.Entities.VwUsersAll", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubLabel")
                        .HasColumnType("longtext");

                    b.HasKey("RecordId");

                    b.ToTable((string)null);

                    b.ToView("vw_users_all", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
