/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Cdr API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type { ApiErrorResponse, TerminationCauseResponse } from "../../models";

import { customFetch } from "../../../custom-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Lista przyczyn zakończenia
 */
export type getTerminationCausesListResponse200 = {
	data: TerminationCauseResponse[];
	status: 200;
};

export type getTerminationCausesListResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type getTerminationCausesListResponseSuccess =
	getTerminationCausesListResponse200 & {
		headers: Headers;
	};
export type getTerminationCausesListResponseError =
	getTerminationCausesListResponse400 & {
		headers: Headers;
	};

export type getTerminationCausesListResponse =
	| getTerminationCausesListResponseSuccess
	| getTerminationCausesListResponseError;

export const getGetTerminationCausesListUrl = () => {
	return `/api/cdr/termination-causes/list`;
};

export const getTerminationCausesList = async (
	options?: RequestInit,
): Promise<getTerminationCausesListResponse> => {
	return customFetch<getTerminationCausesListResponse>(
		getGetTerminationCausesListUrl(),
		{
			...options,
			method: "POST",
		},
	);
};

export const getGetTerminationCausesListMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getTerminationCausesList>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getTerminationCausesList>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["getTerminationCausesList"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getTerminationCausesList>>,
		void
	> = () => {
		return getTerminationCausesList(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetTerminationCausesListMutationResult = NonNullable<
	Awaited<ReturnType<typeof getTerminationCausesList>>
>;

export type GetTerminationCausesListMutationError = ApiErrorResponse;

/**
 * @summary Lista przyczyn zakończenia
 */
export const useGetTerminationCausesList = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getTerminationCausesList>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getTerminationCausesList>>,
	TError,
	void,
	TContext
> => {
	const mutationOptions = getGetTerminationCausesListMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Pobierz przyczynę zakończenia
 */
export type getTerminationCauseByGidResponse200 = {
	data: TerminationCauseResponse;
	status: 200;
};

export type getTerminationCauseByGidResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type getTerminationCauseByGidResponseSuccess =
	getTerminationCauseByGidResponse200 & {
		headers: Headers;
	};
export type getTerminationCauseByGidResponseError =
	getTerminationCauseByGidResponse404 & {
		headers: Headers;
	};

export type getTerminationCauseByGidResponse =
	| getTerminationCauseByGidResponseSuccess
	| getTerminationCauseByGidResponseError;

export const getGetTerminationCauseByGidUrl = (gid: string) => {
	return `/api/cdr/termination-causes/${gid}`;
};

export const getTerminationCauseByGid = async (
	gid: string,
	options?: RequestInit,
): Promise<getTerminationCauseByGidResponse> => {
	return customFetch<getTerminationCauseByGidResponse>(
		getGetTerminationCauseByGidUrl(gid),
		{
			...options,
			method: "GET",
		},
	);
};

export const getGetTerminationCauseByGidQueryKey = (gid?: string) => {
	return [`/api/cdr/termination-causes/${gid}`] as const;
};

export const getGetTerminationCauseByGidQueryOptions = <
	TData = Awaited<ReturnType<typeof getTerminationCauseByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getTerminationCauseByGid>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetTerminationCauseByGidQueryKey(gid);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getTerminationCauseByGid>>
	> = ({ signal }) =>
		getTerminationCauseByGid(gid, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!gid,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getTerminationCauseByGid>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTerminationCauseByGidQueryResult = NonNullable<
	Awaited<ReturnType<typeof getTerminationCauseByGid>>
>;
export type GetTerminationCauseByGidQueryError = ApiErrorResponse;

export function useGetTerminationCauseByGid<
	TData = Awaited<ReturnType<typeof getTerminationCauseByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getTerminationCauseByGid>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getTerminationCauseByGid>>,
					TError,
					Awaited<ReturnType<typeof getTerminationCauseByGid>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTerminationCauseByGid<
	TData = Awaited<ReturnType<typeof getTerminationCauseByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getTerminationCauseByGid>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getTerminationCauseByGid>>,
					TError,
					Awaited<ReturnType<typeof getTerminationCauseByGid>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTerminationCauseByGid<
	TData = Awaited<ReturnType<typeof getTerminationCauseByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getTerminationCauseByGid>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Pobierz przyczynę zakończenia
 */

export function useGetTerminationCauseByGid<
	TData = Awaited<ReturnType<typeof getTerminationCauseByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getTerminationCauseByGid>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetTerminationCauseByGidQueryOptions(gid, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}
