/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Identity API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";

import type {
	ApiErrorResponse,
	JdPrefillResponse,
	MeResponse,
} from "../../models";

import { customFetch } from "../../../custom-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getMeResponse200 = {
	data: MeResponse;
	status: 200;
};

export type getMeResponse401 = {
	data: ApiErrorResponse;
	status: 401;
};

export type getMeResponseSuccess = getMeResponse200 & {
	headers: Headers;
};
export type getMeResponseError = getMeResponse401 & {
	headers: Headers;
};

export type getMeResponse = getMeResponseSuccess | getMeResponseError;

export const getGetMeUrl = () => {
	return `/api/identity/auth/me`;
};

export const getMe = async (options?: RequestInit): Promise<getMeResponse> => {
	return customFetch<getMeResponse>(getGetMeUrl(), {
		...options,
		method: "POST",
	});
};

export const getGetMeMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getMe>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getMe>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["getMe"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getMe>>,
		void
	> = () => {
		return getMe(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetMeMutationResult = NonNullable<
	Awaited<ReturnType<typeof getMe>>
>;

export type GetMeMutationError = ApiErrorResponse;

export const useGetMe = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getMe>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getMe>>,
	TError,
	void,
	TContext
> => {
	const mutationOptions = getGetMeMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
export type getJdPrefillResponse200 = {
	data: JdPrefillResponse;
	status: 200;
};

export type getJdPrefillResponse401 = {
	data: ApiErrorResponse;
	status: 401;
};

export type getJdPrefillResponseSuccess = getJdPrefillResponse200 & {
	headers: Headers;
};
export type getJdPrefillResponseError = getJdPrefillResponse401 & {
	headers: Headers;
};

export type getJdPrefillResponse =
	| getJdPrefillResponseSuccess
	| getJdPrefillResponseError;

export const getGetJdPrefillUrl = () => {
	return `/api/identity/auth/jd-prefill`;
};

export const getJdPrefill = async (
	options?: RequestInit,
): Promise<getJdPrefillResponse> => {
	return customFetch<getJdPrefillResponse>(getGetJdPrefillUrl(), {
		...options,
		method: "POST",
	});
};

export const getGetJdPrefillMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getJdPrefill>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getJdPrefill>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["getJdPrefill"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getJdPrefill>>,
		void
	> = () => {
		return getJdPrefill(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetJdPrefillMutationResult = NonNullable<
	Awaited<ReturnType<typeof getJdPrefill>>
>;

export type GetJdPrefillMutationError = ApiErrorResponse;

export const useGetJdPrefill = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getJdPrefill>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getJdPrefill>>,
	TError,
	void,
	TContext
> => {
	const mutationOptions = getGetJdPrefillMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
