/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rate API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type {
	ApiErrorResponse,
	CreateDestinationGroupRequest,
	DestinationGroupResponse,
} from "../../models";

import { customFetch } from "../../../custom-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Lista grup destynacji
 */
export type getDestinationGroupsResponse200 = {
	data: DestinationGroupResponse[];
	status: 200;
};

export type getDestinationGroupsResponseSuccess =
	getDestinationGroupsResponse200 & {
		headers: Headers;
	};

export type getDestinationGroupsResponse = getDestinationGroupsResponseSuccess;

export const getGetDestinationGroupsUrl = () => {
	return `/api/rate/destination-groups`;
};

export const getDestinationGroups = async (
	options?: RequestInit,
): Promise<getDestinationGroupsResponse> => {
	return customFetch<getDestinationGroupsResponse>(
		getGetDestinationGroupsUrl(),
		{
			...options,
			method: "GET",
		},
	);
};

export const getGetDestinationGroupsQueryKey = () => {
	return [`/api/rate/destination-groups`] as const;
};

export const getGetDestinationGroupsQueryOptions = <
	TData = Awaited<ReturnType<typeof getDestinationGroups>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getDestinationGroups>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof customFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetDestinationGroupsQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getDestinationGroups>>
	> = ({ signal }) => getDestinationGroups({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getDestinationGroups>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDestinationGroupsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getDestinationGroups>>
>;
export type GetDestinationGroupsQueryError = unknown;

export function useGetDestinationGroups<
	TData = Awaited<ReturnType<typeof getDestinationGroups>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDestinationGroups>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDestinationGroups>>,
					TError,
					Awaited<ReturnType<typeof getDestinationGroups>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDestinationGroups<
	TData = Awaited<ReturnType<typeof getDestinationGroups>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDestinationGroups>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDestinationGroups>>,
					TError,
					Awaited<ReturnType<typeof getDestinationGroups>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDestinationGroups<
	TData = Awaited<ReturnType<typeof getDestinationGroups>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDestinationGroups>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Lista grup destynacji
 */

export function useGetDestinationGroups<
	TData = Awaited<ReturnType<typeof getDestinationGroups>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDestinationGroups>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetDestinationGroupsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * @summary Utwórz grupę destynacji
 */
export type createDestinationGroupResponse200 = {
	data: DestinationGroupResponse;
	status: 200;
};

export type createDestinationGroupResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type createDestinationGroupResponseSuccess =
	createDestinationGroupResponse200 & {
		headers: Headers;
	};
export type createDestinationGroupResponseError =
	createDestinationGroupResponse400 & {
		headers: Headers;
	};

export type createDestinationGroupResponse =
	| createDestinationGroupResponseSuccess
	| createDestinationGroupResponseError;

export const getCreateDestinationGroupUrl = () => {
	return `/api/rate/destination-groups`;
};

export const createDestinationGroup = async (
	createDestinationGroupRequest: CreateDestinationGroupRequest,
	options?: RequestInit,
): Promise<createDestinationGroupResponse> => {
	return customFetch<createDestinationGroupResponse>(
		getCreateDestinationGroupUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(createDestinationGroupRequest),
		},
	);
};

export const getCreateDestinationGroupMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createDestinationGroup>>,
		TError,
		{ data: CreateDestinationGroupRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createDestinationGroup>>,
	TError,
	{ data: CreateDestinationGroupRequest },
	TContext
> => {
	const mutationKey = ["createDestinationGroup"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createDestinationGroup>>,
		{ data: CreateDestinationGroupRequest }
	> = (props) => {
		const { data } = props ?? {};

		return createDestinationGroup(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateDestinationGroupMutationResult = NonNullable<
	Awaited<ReturnType<typeof createDestinationGroup>>
>;
export type CreateDestinationGroupMutationBody = CreateDestinationGroupRequest;
export type CreateDestinationGroupMutationError = ApiErrorResponse;

/**
 * @summary Utwórz grupę destynacji
 */
export const useCreateDestinationGroup = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createDestinationGroup>>,
			TError,
			{ data: CreateDestinationGroupRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createDestinationGroup>>,
	TError,
	{ data: CreateDestinationGroupRequest },
	TContext
> => {
	const mutationOptions = getCreateDestinationGroupMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Pobierz grupę destynacji
 */
export type getDestinationGroupByIdResponse200 = {
	data: DestinationGroupResponse;
	status: 200;
};

export type getDestinationGroupByIdResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type getDestinationGroupByIdResponseSuccess =
	getDestinationGroupByIdResponse200 & {
		headers: Headers;
	};
export type getDestinationGroupByIdResponseError =
	getDestinationGroupByIdResponse404 & {
		headers: Headers;
	};

export type getDestinationGroupByIdResponse =
	| getDestinationGroupByIdResponseSuccess
	| getDestinationGroupByIdResponseError;

export const getGetDestinationGroupByIdUrl = (id: number) => {
	return `/api/rate/destination-groups/${id}`;
};

export const getDestinationGroupById = async (
	id: number,
	options?: RequestInit,
): Promise<getDestinationGroupByIdResponse> => {
	return customFetch<getDestinationGroupByIdResponse>(
		getGetDestinationGroupByIdUrl(id),
		{
			...options,
			method: "GET",
		},
	);
};

export const getGetDestinationGroupByIdQueryKey = (id?: number) => {
	return [`/api/rate/destination-groups/${id}`] as const;
};

export const getGetDestinationGroupByIdQueryOptions = <
	TData = Awaited<ReturnType<typeof getDestinationGroupById>>,
	TError = ApiErrorResponse,
>(
	id: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDestinationGroupById>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetDestinationGroupByIdQueryKey(id);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getDestinationGroupById>>
	> = ({ signal }) =>
		getDestinationGroupById(id, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getDestinationGroupById>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDestinationGroupByIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof getDestinationGroupById>>
>;
export type GetDestinationGroupByIdQueryError = ApiErrorResponse;

export function useGetDestinationGroupById<
	TData = Awaited<ReturnType<typeof getDestinationGroupById>>,
	TError = ApiErrorResponse,
>(
	id: number,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDestinationGroupById>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDestinationGroupById>>,
					TError,
					Awaited<ReturnType<typeof getDestinationGroupById>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDestinationGroupById<
	TData = Awaited<ReturnType<typeof getDestinationGroupById>>,
	TError = ApiErrorResponse,
>(
	id: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDestinationGroupById>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getDestinationGroupById>>,
					TError,
					Awaited<ReturnType<typeof getDestinationGroupById>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDestinationGroupById<
	TData = Awaited<ReturnType<typeof getDestinationGroupById>>,
	TError = ApiErrorResponse,
>(
	id: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDestinationGroupById>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Pobierz grupę destynacji
 */

export function useGetDestinationGroupById<
	TData = Awaited<ReturnType<typeof getDestinationGroupById>>,
	TError = ApiErrorResponse,
>(
	id: number,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getDestinationGroupById>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetDestinationGroupByIdQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * @summary Aktualizuj grupę destynacji
 */
export type updateDestinationGroupResponse200 = {
	data: DestinationGroupResponse;
	status: 200;
};

export type updateDestinationGroupResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type updateDestinationGroupResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type updateDestinationGroupResponseSuccess =
	updateDestinationGroupResponse200 & {
		headers: Headers;
	};
export type updateDestinationGroupResponseError = (
	| updateDestinationGroupResponse400
	| updateDestinationGroupResponse404
) & {
	headers: Headers;
};

export type updateDestinationGroupResponse =
	| updateDestinationGroupResponseSuccess
	| updateDestinationGroupResponseError;

export const getUpdateDestinationGroupUrl = (id: number) => {
	return `/api/rate/destination-groups/${id}`;
};

export const updateDestinationGroup = async (
	id: number,
	createDestinationGroupRequest: CreateDestinationGroupRequest,
	options?: RequestInit,
): Promise<updateDestinationGroupResponse> => {
	return customFetch<updateDestinationGroupResponse>(
		getUpdateDestinationGroupUrl(id),
		{
			...options,
			method: "PUT",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(createDestinationGroupRequest),
		},
	);
};

export const getUpdateDestinationGroupMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateDestinationGroup>>,
		TError,
		{ id: number; data: CreateDestinationGroupRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateDestinationGroup>>,
	TError,
	{ id: number; data: CreateDestinationGroupRequest },
	TContext
> => {
	const mutationKey = ["updateDestinationGroup"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateDestinationGroup>>,
		{ id: number; data: CreateDestinationGroupRequest }
	> = (props) => {
		const { id, data } = props ?? {};

		return updateDestinationGroup(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateDestinationGroupMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateDestinationGroup>>
>;
export type UpdateDestinationGroupMutationBody = CreateDestinationGroupRequest;
export type UpdateDestinationGroupMutationError = ApiErrorResponse;

/**
 * @summary Aktualizuj grupę destynacji
 */
export const useUpdateDestinationGroup = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateDestinationGroup>>,
			TError,
			{ id: number; data: CreateDestinationGroupRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateDestinationGroup>>,
	TError,
	{ id: number; data: CreateDestinationGroupRequest },
	TContext
> => {
	const mutationOptions = getUpdateDestinationGroupMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
