// <auto-generated />
using System;
using FinCosts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinCosts.Data.Migrations
{
    [DbContext(typeof(FinCostsDbContext))]
    [Migration("20260208140510_Initial mig")]
    partial class Initialmig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FinCosts.Data.Entities.CostDocumentTypeDict", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("category");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameEN")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name_en");

                    b.Property<string>("NamePL")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name_pl");

                    b.HasKey("Id");

                    b.HasIndex("NameEN")
                        .IsUnique();

                    b.HasIndex("NamePL")
                        .IsUnique();

                    b.ToTable("cost_document_type", (string)null);
                });

            modelBuilder.Entity("FinCosts.Data.Entities.CurrencyTypeDict", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("category");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("NameEN")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name_en");

                    b.Property<string>("NamePL")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name_pl");

                    b.HasKey("Id");

                    b.HasIndex("NameEN")
                        .IsUnique();

                    b.HasIndex("NamePL")
                        .IsUnique();

                    b.ToTable("currency_type", (string)null);
                });

            modelBuilder.Entity("FinCosts.Data.Entities.DocumentEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<decimal?>("CurrencyForeignRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("currency_foreign_rate");

                    b.Property<string>("CurrencyNamePL")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("currency_name_pl");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("document_type_id");

                    b.Property<string>("DocumentTypeNamePL")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("document_type_name_pl");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("gid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("issued_by");

                    b.Property<string>("IssuedFor")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("issued_for");

                    b.Property<string>("IssuedForVatNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("issued_for_vat_number");

                    b.Property<string>("IssuedVatNumber")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("issued_vat_number");

                    b.Property<string>("KSEAccountNumber")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("kse_account_number");

                    b.Property<string>("KSERefNumber")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("kse_ref_number");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<long?>("ModifiedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_by_user_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("vat_rate");

                    b.Property<bool>("WasPaid")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("was_paid");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyNamePL");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("Gid")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IssuedForVatNumber");

                    b.HasIndex("IssuedVatNumber");

                    b.ToTable("document_entry", (string)null);
                });

            modelBuilder.Entity("FinCosts.Data.Entities.VatRateTypeDict", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("NameEN")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name_en");

                    b.Property<string>("NamePL")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name_pl");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("vat_rate");

                    b.HasKey("Id");

                    b.HasIndex("NameEN")
                        .IsUnique();

                    b.HasIndex("NamePL")
                        .IsUnique();

                    b.HasIndex("VatRate");

                    b.ToTable("vat_rate_type", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
