/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rate API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface CreateRateRequest {
	/** @nullable */
	tariffGid?: string | null;
	/** @nullable */
	prefix?: string | null;
	/** @nullable */
	destinationName?: string | null;
	ratePerMinute?: number;
	/** @nullable */
	connectionFee?: number | null;
	/** @nullable */
	billingIncrement?: number | null;
	/** @nullable */
	minimumDuration?: number | null;
	/** @nullable */
	effectiveFrom?: string | null;
	/** @nullable */
	effectiveTo?: string | null;
	/** @nullable */
	destinationGroupId?: number | null;
	/** @nullable */
	notes?: string | null;
}
