/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rate API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface CreateTariffRequest {
	/** @nullable */
	name?: string | null;
	/** @nullable */
	description?: string | null;
	/** @nullable */
	currencyCode?: string | null;
	isDefault?: boolean;
	/** @nullable */
	validFrom?: string | null;
	/** @nullable */
	validTo?: string | null;
	billingIncrement?: number;
	minimumDuration?: number;
	connectionFee?: number;
}
