/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rate API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface DestinationGroupResponse {
	id?: number;
	/** @nullable */
	name?: string | null;
	/** @nullable */
	namePL?: string | null;
	/** @nullable */
	nameEN?: string | null;
	/** @nullable */
	description?: string | null;
	isActive?: boolean;
}
