/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rate API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export type LookupRateParams = {
	tariffGid: string;
	phoneNumber: string;
};
