/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rate API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { RateResponse } from "./rateResponse";

export interface RateResponsePagedResult {
	/** @nullable */
	items?: RateResponse[] | null;
	totalCount?: number;
	pageNumber?: number;
	pageSize?: number;
	readonly totalPages?: number;
	readonly hasPreviousPage?: boolean;
	readonly hasNextPage?: boolean;
}
