/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rate API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface RateListFilter {
	pageNumber?: number;
	pageSize?: number;
	/** @nullable */
	search?: string | null;
	/** @nullable */
	tariffGid?: string | null;
	/** @nullable */
	prefix?: string | null;
	/** @nullable */
	destinationGroupId?: number | null;
	/** @nullable */
	isActive?: boolean | null;
}
