/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rate API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface RateResponse {
	/** @nullable */
	gid?: string | null;
	/** @nullable */
	prefix?: string | null;
	/** @nullable */
	destinationName?: string | null;
	ratePerMinute?: number;
	/** @nullable */
	connectionFee?: number | null;
	/** @nullable */
	billingIncrement?: number | null;
	/** @nullable */
	minimumDuration?: number | null;
	effectiveFrom?: string;
	/** @nullable */
	effectiveTo?: string | null;
	isActive?: boolean;
	/** @nullable */
	notes?: string | null;
	/** @nullable */
	tariffGid?: string | null;
	/** @nullable */
	tariffName?: string | null;
	/** @nullable */
	destinationGroupName?: string | null;
	createdAt?: string;
}
