/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rate API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface TariffRateResponse {
	/** @nullable */
	gid?: string | null;
	/** @nullable */
	prefix?: string | null;
	/** @nullable */
	destinationName?: string | null;
	ratePerMinute?: number;
	isActive?: boolean;
}
