/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rate API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface TariffResponse {
	/** @nullable */
	gid?: string | null;
	/** @nullable */
	name?: string | null;
	/** @nullable */
	description?: string | null;
	/** @nullable */
	currencyCode?: string | null;
	isDefault?: boolean;
	isActive?: boolean;
	validFrom?: string;
	/** @nullable */
	validTo?: string | null;
	billingIncrement?: number;
	minimumDuration?: number;
	connectionFee?: number;
	ratesCount?: number;
	createdAt?: string;
}
