/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX AnswerRule API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type {
	AnsweringRuleDetailResponse,
	AnsweringRuleListFilter,
	AnsweringRuleResponsePagedResult,
	ApiErrorResponse,
	CheckRuleRequest,
	CheckRuleResponse,
	CreateAnsweringRuleRequest,
	UpdateAnsweringRuleRequest,
} from "../../models";

import { customFetch } from "../../../custom-fetch";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
	T,
>() => T extends Y ? 1 : 2
	? A
	: B;

type WritableKeys<T> = {
	[P in keyof T]-?: IfEquals<
		{ [Q in P]: T[P] },
		{ -readonly [Q in P]: T[P] },
		P
	>;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
	k: infer I,
) => void
	? I
	: never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
	? {
			[P in keyof Writable<T>]: T[P] extends object
				? NonReadonly<NonNullable<T[P]>>
				: T[P];
		}
	: DistributeReadOnlyOverUnions<T>;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Lista reguł odpowiadania
 */
export type getRulesListResponse200 = {
	data: AnsweringRuleResponsePagedResult;
	status: 200;
};

export type getRulesListResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type getRulesListResponseSuccess = getRulesListResponse200 & {
	headers: Headers;
};
export type getRulesListResponseError = getRulesListResponse400 & {
	headers: Headers;
};

export type getRulesListResponse =
	| getRulesListResponseSuccess
	| getRulesListResponseError;

export const getGetRulesListUrl = () => {
	return `/api/answerrule/rules/list`;
};

export const getRulesList = async (
	answeringRuleListFilter: NonReadonly<AnsweringRuleListFilter>,
	options?: RequestInit,
): Promise<getRulesListResponse> => {
	return customFetch<getRulesListResponse>(getGetRulesListUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(answeringRuleListFilter),
	});
};

export const getGetRulesListMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getRulesList>>,
		TError,
		{ data: NonReadonly<AnsweringRuleListFilter> },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getRulesList>>,
	TError,
	{ data: NonReadonly<AnsweringRuleListFilter> },
	TContext
> => {
	const mutationKey = ["getRulesList"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getRulesList>>,
		{ data: NonReadonly<AnsweringRuleListFilter> }
	> = (props) => {
		const { data } = props ?? {};

		return getRulesList(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetRulesListMutationResult = NonNullable<
	Awaited<ReturnType<typeof getRulesList>>
>;
export type GetRulesListMutationBody = NonReadonly<AnsweringRuleListFilter>;
export type GetRulesListMutationError = ApiErrorResponse;

/**
 * @summary Lista reguł odpowiadania
 */
export const useGetRulesList = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getRulesList>>,
			TError,
			{ data: NonReadonly<AnsweringRuleListFilter> },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getRulesList>>,
	TError,
	{ data: NonReadonly<AnsweringRuleListFilter> },
	TContext
> => {
	const mutationOptions = getGetRulesListMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Pobierz regułę
 */
export type getRuleByGidResponse200 = {
	data: AnsweringRuleDetailResponse;
	status: 200;
};

export type getRuleByGidResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type getRuleByGidResponseSuccess = getRuleByGidResponse200 & {
	headers: Headers;
};
export type getRuleByGidResponseError = getRuleByGidResponse404 & {
	headers: Headers;
};

export type getRuleByGidResponse =
	| getRuleByGidResponseSuccess
	| getRuleByGidResponseError;

export const getGetRuleByGidUrl = (gid: string) => {
	return `/api/answerrule/rules/${gid}`;
};

export const getRuleByGid = async (
	gid: string,
	options?: RequestInit,
): Promise<getRuleByGidResponse> => {
	return customFetch<getRuleByGidResponse>(getGetRuleByGidUrl(gid), {
		...options,
		method: "GET",
	});
};

export const getGetRuleByGidQueryKey = (gid?: string) => {
	return [`/api/answerrule/rules/${gid}`] as const;
};

export const getGetRuleByGidQueryOptions = <
	TData = Awaited<ReturnType<typeof getRuleByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getRuleByGid>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetRuleByGidQueryKey(gid);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getRuleByGid>>> = ({
		signal,
	}) => getRuleByGid(gid, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!gid,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getRuleByGid>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRuleByGidQueryResult = NonNullable<
	Awaited<ReturnType<typeof getRuleByGid>>
>;
export type GetRuleByGidQueryError = ApiErrorResponse;

export function useGetRuleByGid<
	TData = Awaited<ReturnType<typeof getRuleByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getRuleByGid>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getRuleByGid>>,
					TError,
					Awaited<ReturnType<typeof getRuleByGid>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRuleByGid<
	TData = Awaited<ReturnType<typeof getRuleByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getRuleByGid>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getRuleByGid>>,
					TError,
					Awaited<ReturnType<typeof getRuleByGid>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRuleByGid<
	TData = Awaited<ReturnType<typeof getRuleByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getRuleByGid>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Pobierz regułę
 */

export function useGetRuleByGid<
	TData = Awaited<ReturnType<typeof getRuleByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getRuleByGid>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetRuleByGidQueryOptions(gid, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * @summary Aktualizuj regułę
 */
export type updateRuleResponse200 = {
	data: AnsweringRuleDetailResponse;
	status: 200;
};

export type updateRuleResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type updateRuleResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type updateRuleResponseSuccess = updateRuleResponse200 & {
	headers: Headers;
};
export type updateRuleResponseError = (
	| updateRuleResponse400
	| updateRuleResponse404
) & {
	headers: Headers;
};

export type updateRuleResponse =
	| updateRuleResponseSuccess
	| updateRuleResponseError;

export const getUpdateRuleUrl = (gid: string) => {
	return `/api/answerrule/rules/${gid}`;
};

export const updateRule = async (
	gid: string,
	updateAnsweringRuleRequest: UpdateAnsweringRuleRequest,
	options?: RequestInit,
): Promise<updateRuleResponse> => {
	return customFetch<updateRuleResponse>(getUpdateRuleUrl(gid), {
		...options,
		method: "PUT",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(updateAnsweringRuleRequest),
	});
};

export const getUpdateRuleMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateRule>>,
		TError,
		{ gid: string; data: UpdateAnsweringRuleRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateRule>>,
	TError,
	{ gid: string; data: UpdateAnsweringRuleRequest },
	TContext
> => {
	const mutationKey = ["updateRule"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateRule>>,
		{ gid: string; data: UpdateAnsweringRuleRequest }
	> = (props) => {
		const { gid, data } = props ?? {};

		return updateRule(gid, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateRuleMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateRule>>
>;
export type UpdateRuleMutationBody = UpdateAnsweringRuleRequest;
export type UpdateRuleMutationError = ApiErrorResponse;

/**
 * @summary Aktualizuj regułę
 */
export const useUpdateRule = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateRule>>,
			TError,
			{ gid: string; data: UpdateAnsweringRuleRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateRule>>,
	TError,
	{ gid: string; data: UpdateAnsweringRuleRequest },
	TContext
> => {
	const mutationOptions = getUpdateRuleMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Usuń regułę
 */
export type deleteRuleResponse200 = {
	data: boolean;
	status: 200;
};

export type deleteRuleResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type deleteRuleResponseSuccess = deleteRuleResponse200 & {
	headers: Headers;
};
export type deleteRuleResponseError = deleteRuleResponse404 & {
	headers: Headers;
};

export type deleteRuleResponse =
	| deleteRuleResponseSuccess
	| deleteRuleResponseError;

export const getDeleteRuleUrl = (gid: string) => {
	return `/api/answerrule/rules/${gid}`;
};

export const deleteRule = async (
	gid: string,
	options?: RequestInit,
): Promise<deleteRuleResponse> => {
	return customFetch<deleteRuleResponse>(getDeleteRuleUrl(gid), {
		...options,
		method: "DELETE",
	});
};

export const getDeleteRuleMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteRule>>,
		TError,
		{ gid: string },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteRule>>,
	TError,
	{ gid: string },
	TContext
> => {
	const mutationKey = ["deleteRule"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteRule>>,
		{ gid: string }
	> = (props) => {
		const { gid } = props ?? {};

		return deleteRule(gid, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteRuleMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteRule>>
>;

export type DeleteRuleMutationError = ApiErrorResponse;

/**
 * @summary Usuń regułę
 */
export const useDeleteRule = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteRule>>,
			TError,
			{ gid: string },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteRule>>,
	TError,
	{ gid: string },
	TContext
> => {
	const mutationOptions = getDeleteRuleMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Utwórz regułę
 */
export type createRuleResponse200 = {
	data: AnsweringRuleDetailResponse;
	status: 200;
};

export type createRuleResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type createRuleResponseSuccess = createRuleResponse200 & {
	headers: Headers;
};
export type createRuleResponseError = createRuleResponse400 & {
	headers: Headers;
};

export type createRuleResponse =
	| createRuleResponseSuccess
	| createRuleResponseError;

export const getCreateRuleUrl = () => {
	return `/api/answerrule/rules`;
};

export const createRule = async (
	createAnsweringRuleRequest: CreateAnsweringRuleRequest,
	options?: RequestInit,
): Promise<createRuleResponse> => {
	return customFetch<createRuleResponse>(getCreateRuleUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(createAnsweringRuleRequest),
	});
};

export const getCreateRuleMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createRule>>,
		TError,
		{ data: CreateAnsweringRuleRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createRule>>,
	TError,
	{ data: CreateAnsweringRuleRequest },
	TContext
> => {
	const mutationKey = ["createRule"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createRule>>,
		{ data: CreateAnsweringRuleRequest }
	> = (props) => {
		const { data } = props ?? {};

		return createRule(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateRuleMutationResult = NonNullable<
	Awaited<ReturnType<typeof createRule>>
>;
export type CreateRuleMutationBody = CreateAnsweringRuleRequest;
export type CreateRuleMutationError = ApiErrorResponse;

/**
 * @summary Utwórz regułę
 */
export const useCreateRule = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createRule>>,
			TError,
			{ data: CreateAnsweringRuleRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createRule>>,
	TError,
	{ data: CreateAnsweringRuleRequest },
	TContext
> => {
	const mutationOptions = getCreateRuleMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Włącz/wyłącz regułę
 */
export type toggleRuleResponse200 = {
	data: AnsweringRuleDetailResponse;
	status: 200;
};

export type toggleRuleResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type toggleRuleResponseSuccess = toggleRuleResponse200 & {
	headers: Headers;
};
export type toggleRuleResponseError = toggleRuleResponse404 & {
	headers: Headers;
};

export type toggleRuleResponse =
	| toggleRuleResponseSuccess
	| toggleRuleResponseError;

export const getToggleRuleUrl = (gid: string) => {
	return `/api/answerrule/rules/${gid}/toggle`;
};

export const toggleRule = async (
	gid: string,
	options?: RequestInit,
): Promise<toggleRuleResponse> => {
	return customFetch<toggleRuleResponse>(getToggleRuleUrl(gid), {
		...options,
		method: "PATCH",
	});
};

export const getToggleRuleMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof toggleRule>>,
		TError,
		{ gid: string },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof toggleRule>>,
	TError,
	{ gid: string },
	TContext
> => {
	const mutationKey = ["toggleRule"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof toggleRule>>,
		{ gid: string }
	> = (props) => {
		const { gid } = props ?? {};

		return toggleRule(gid, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ToggleRuleMutationResult = NonNullable<
	Awaited<ReturnType<typeof toggleRule>>
>;

export type ToggleRuleMutationError = ApiErrorResponse;

/**
 * @summary Włącz/wyłącz regułę
 */
export const useToggleRule = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof toggleRule>>,
			TError,
			{ gid: string },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof toggleRule>>,
	TError,
	{ gid: string },
	TContext
> => {
	const mutationOptions = getToggleRuleMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Sprawdź aktywną regułę dla konta SIP
 */
export type checkActiveRuleResponse200 = {
	data: CheckRuleResponse;
	status: 200;
};

export type checkActiveRuleResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type checkActiveRuleResponseSuccess = checkActiveRuleResponse200 & {
	headers: Headers;
};
export type checkActiveRuleResponseError = checkActiveRuleResponse400 & {
	headers: Headers;
};

export type checkActiveRuleResponse =
	| checkActiveRuleResponseSuccess
	| checkActiveRuleResponseError;

export const getCheckActiveRuleUrl = () => {
	return `/api/answerrule/check`;
};

export const checkActiveRule = async (
	checkRuleRequest: CheckRuleRequest,
	options?: RequestInit,
): Promise<checkActiveRuleResponse> => {
	return customFetch<checkActiveRuleResponse>(getCheckActiveRuleUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(checkRuleRequest),
	});
};

export const getCheckActiveRuleMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof checkActiveRule>>,
		TError,
		{ data: CheckRuleRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof checkActiveRule>>,
	TError,
	{ data: CheckRuleRequest },
	TContext
> => {
	const mutationKey = ["checkActiveRule"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof checkActiveRule>>,
		{ data: CheckRuleRequest }
	> = (props) => {
		const { data } = props ?? {};

		return checkActiveRule(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CheckActiveRuleMutationResult = NonNullable<
	Awaited<ReturnType<typeof checkActiveRule>>
>;
export type CheckActiveRuleMutationBody = CheckRuleRequest;
export type CheckActiveRuleMutationError = ApiErrorResponse;

/**
 * @summary Sprawdź aktywną regułę dla konta SIP
 */
export const useCheckActiveRule = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof checkActiveRule>>,
			TError,
			{ data: CheckRuleRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof checkActiveRule>>,
	TError,
	{ data: CheckRuleRequest },
	TContext
> => {
	const mutationOptions = getCheckActiveRuleMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
