/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Cdr API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type { ApiErrorResponse, CallDirectionResponse } from "../../models";

import { customFetch } from "../../../custom-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Lista kierunków połączeń
 */
export type getCallDirectionsListResponse200 = {
	data: CallDirectionResponse[];
	status: 200;
};

export type getCallDirectionsListResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type getCallDirectionsListResponseSuccess =
	getCallDirectionsListResponse200 & {
		headers: Headers;
	};
export type getCallDirectionsListResponseError =
	getCallDirectionsListResponse400 & {
		headers: Headers;
	};

export type getCallDirectionsListResponse =
	| getCallDirectionsListResponseSuccess
	| getCallDirectionsListResponseError;

export const getGetCallDirectionsListUrl = () => {
	return `/api/cdr/call-directions/list`;
};

export const getCallDirectionsList = async (
	options?: RequestInit,
): Promise<getCallDirectionsListResponse> => {
	return customFetch<getCallDirectionsListResponse>(
		getGetCallDirectionsListUrl(),
		{
			...options,
			method: "POST",
		},
	);
};

export const getGetCallDirectionsListMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getCallDirectionsList>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getCallDirectionsList>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["getCallDirectionsList"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getCallDirectionsList>>,
		void
	> = () => {
		return getCallDirectionsList(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetCallDirectionsListMutationResult = NonNullable<
	Awaited<ReturnType<typeof getCallDirectionsList>>
>;

export type GetCallDirectionsListMutationError = ApiErrorResponse;

/**
 * @summary Lista kierunków połączeń
 */
export const useGetCallDirectionsList = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getCallDirectionsList>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getCallDirectionsList>>,
	TError,
	void,
	TContext
> => {
	const mutationOptions = getGetCallDirectionsListMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Pobierz kierunek połączenia
 */
export type getCallDirectionByGidResponse200 = {
	data: CallDirectionResponse;
	status: 200;
};

export type getCallDirectionByGidResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type getCallDirectionByGidResponseSuccess =
	getCallDirectionByGidResponse200 & {
		headers: Headers;
	};
export type getCallDirectionByGidResponseError =
	getCallDirectionByGidResponse404 & {
		headers: Headers;
	};

export type getCallDirectionByGidResponse =
	| getCallDirectionByGidResponseSuccess
	| getCallDirectionByGidResponseError;

export const getGetCallDirectionByGidUrl = (gid: string) => {
	return `/api/cdr/call-directions/${gid}`;
};

export const getCallDirectionByGid = async (
	gid: string,
	options?: RequestInit,
): Promise<getCallDirectionByGidResponse> => {
	return customFetch<getCallDirectionByGidResponse>(
		getGetCallDirectionByGidUrl(gid),
		{
			...options,
			method: "GET",
		},
	);
};

export const getGetCallDirectionByGidQueryKey = (gid?: string) => {
	return [`/api/cdr/call-directions/${gid}`] as const;
};

export const getGetCallDirectionByGidQueryOptions = <
	TData = Awaited<ReturnType<typeof getCallDirectionByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCallDirectionByGid>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetCallDirectionByGidQueryKey(gid);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getCallDirectionByGid>>
	> = ({ signal }) => getCallDirectionByGid(gid, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!gid,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getCallDirectionByGid>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCallDirectionByGidQueryResult = NonNullable<
	Awaited<ReturnType<typeof getCallDirectionByGid>>
>;
export type GetCallDirectionByGidQueryError = ApiErrorResponse;

export function useGetCallDirectionByGid<
	TData = Awaited<ReturnType<typeof getCallDirectionByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCallDirectionByGid>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getCallDirectionByGid>>,
					TError,
					Awaited<ReturnType<typeof getCallDirectionByGid>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCallDirectionByGid<
	TData = Awaited<ReturnType<typeof getCallDirectionByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCallDirectionByGid>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getCallDirectionByGid>>,
					TError,
					Awaited<ReturnType<typeof getCallDirectionByGid>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCallDirectionByGid<
	TData = Awaited<ReturnType<typeof getCallDirectionByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCallDirectionByGid>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Pobierz kierunek połączenia
 */

export function useGetCallDirectionByGid<
	TData = Awaited<ReturnType<typeof getCallDirectionByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCallDirectionByGid>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetCallDirectionByGidQueryOptions(gid, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}
