// <auto-generated />
using System;
using CdrService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CdrService.Data.Migrations
{
    [DbContext(typeof(CdrDbContext))]
    [Migration("20260201084500_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CdrService.Data.Entities.CallDirection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("gid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NamePL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_pl");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Gid")
                        .IsUnique();

                    b.ToTable("call_directions", (string)null);
                });

            modelBuilder.Entity("CdrService.Data.Entities.CallRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AnswerTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("answer_time");

                    b.Property<int>("BillableSeconds")
                        .HasColumnType("int")
                        .HasColumnName("billable_seconds");

                    b.Property<int>("BillingIncrement")
                        .HasColumnType("int")
                        .HasColumnName("billing_increment");

                    b.Property<long>("CallDirectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("call_direction_id");

                    b.Property<long>("CallStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("call_status_id");

                    b.Property<string>("CallUuid")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("call_uuid");

                    b.Property<string>("CalledNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("called_number");

                    b.Property<string>("CallerId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("caller_id");

                    b.Property<decimal>("ConnectionFee")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("connection_fee");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("CustomerGid")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("customer_gid");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("customer_name");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DestinationGatewayGid")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("destination_gateway_gid");

                    b.Property<string>("DestinationGatewayName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("destination_gateway_name");

                    b.Property<string>("DestinationName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("destination_name");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_time");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("gid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MatchedPrefix")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("matched_prefix");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<long?>("ModifiedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_by_user_id");

                    b.Property<decimal>("RatePerMinute")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("rate_per_minute");

                    b.Property<string>("RawCdrJson")
                        .HasColumnType("text")
                        .HasColumnName("raw_cdr_json");

                    b.Property<string>("SipAccountGid")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("sip_account_gid");

                    b.Property<string>("SipAccountUsername")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sip_account_username");

                    b.Property<string>("SourceGatewayGid")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("source_gateway_gid");

                    b.Property<string>("SourceGatewayName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("source_gateway_name");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.Property<string>("TariffGid")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("tariff_gid");

                    b.Property<string>("TariffName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tariff_name");

                    b.Property<long>("TerminationCauseId")
                        .HasColumnType("bigint")
                        .HasColumnName("termination_cause_id");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("total_cost");

                    b.Property<string>("UserData")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("user_data");

                    b.HasKey("Id");

                    b.HasIndex("CallDirectionId");

                    b.HasIndex("CallStatusId");

                    b.HasIndex("CallUuid");

                    b.HasIndex("CalledNumber");

                    b.HasIndex("CallerId");

                    b.HasIndex("CustomerGid");

                    b.HasIndex("Gid")
                        .IsUnique();

                    b.HasIndex("SipAccountGid");

                    b.HasIndex("StartTime");

                    b.HasIndex("TerminationCauseId");

                    b.HasIndex("CustomerGid", "StartTime");

                    b.HasIndex("StartTime", "CallStatusId");

                    b.ToTable("call_records", (string)null);
                });

            modelBuilder.Entity("CdrService.Data.Entities.CallStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("gid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NamePL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_pl");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Gid")
                        .IsUnique();

                    b.ToTable("call_statuses", (string)null);
                });

            modelBuilder.Entity("CdrService.Data.Entities.TerminationCause", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("gid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NamePL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_pl");

                    b.Property<int?>("Q850Code")
                        .HasColumnType("int")
                        .HasColumnName("q850_code");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Gid")
                        .IsUnique();

                    b.HasIndex("Q850Code");

                    b.ToTable("termination_causes", (string)null);
                });

            modelBuilder.Entity("CdrService.Data.Entities.CallRecord", b =>
                {
                    b.HasOne("CdrService.Data.Entities.CallDirection", "CallDirection")
                        .WithMany("CallRecords")
                        .HasForeignKey("CallDirectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CdrService.Data.Entities.CallStatus", "CallStatus")
                        .WithMany("CallRecords")
                        .HasForeignKey("CallStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CdrService.Data.Entities.TerminationCause", "TerminationCause")
                        .WithMany("CallRecords")
                        .HasForeignKey("TerminationCauseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CallDirection");

                    b.Navigation("CallStatus");

                    b.Navigation("TerminationCause");
                });

            modelBuilder.Entity("CdrService.Data.Entities.CallDirection", b =>
                {
                    b.Navigation("CallRecords");
                });

            modelBuilder.Entity("CdrService.Data.Entities.CallStatus", b =>
                {
                    b.Navigation("CallRecords");
                });

            modelBuilder.Entity("CdrService.Data.Entities.TerminationCause", b =>
                {
                    b.Navigation("CallRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
