/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rcp API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";

import type {
	ApiErrorResponse,
	ChangeStatusRequest,
	GetByGidRequest,
	GetPeriodRequest,
	MonitorPeriodResponse,
	MonthlyEntryResponse,
	PeriodSummaryResponse,
} from "../../models";

import { customFetch } from "../../../custom-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Lista wpisów do zatwierdzenia
 */
export type getSupervisorPeriodEntriesResponse200 = {
	data: PeriodSummaryResponse;
	status: 200;
};

export type getSupervisorPeriodEntriesResponseSuccess =
	getSupervisorPeriodEntriesResponse200 & {
		headers: Headers;
	};

export type getSupervisorPeriodEntriesResponse =
	getSupervisorPeriodEntriesResponseSuccess;

export const getGetSupervisorPeriodEntriesUrl = () => {
	return `/api/rcp/supervisor/period`;
};

export const getSupervisorPeriodEntries = async (
	getPeriodRequest: GetPeriodRequest,
	options?: RequestInit,
): Promise<getSupervisorPeriodEntriesResponse> => {
	return customFetch<getSupervisorPeriodEntriesResponse>(
		getGetSupervisorPeriodEntriesUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(getPeriodRequest),
		},
	);
};

export const getGetSupervisorPeriodEntriesMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getSupervisorPeriodEntries>>,
		TError,
		{ data: GetPeriodRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getSupervisorPeriodEntries>>,
	TError,
	{ data: GetPeriodRequest },
	TContext
> => {
	const mutationKey = ["getSupervisorPeriodEntries"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getSupervisorPeriodEntries>>,
		{ data: GetPeriodRequest }
	> = (props) => {
		const { data } = props ?? {};

		return getSupervisorPeriodEntries(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetSupervisorPeriodEntriesMutationResult = NonNullable<
	Awaited<ReturnType<typeof getSupervisorPeriodEntries>>
>;
export type GetSupervisorPeriodEntriesMutationBody = GetPeriodRequest;
export type GetSupervisorPeriodEntriesMutationError = unknown;

/**
 * @summary Lista wpisów do zatwierdzenia
 */
export const useGetSupervisorPeriodEntries = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getSupervisorPeriodEntries>>,
			TError,
			{ data: GetPeriodRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getSupervisorPeriodEntries>>,
	TError,
	{ data: GetPeriodRequest },
	TContext
> => {
	const mutationOptions = getGetSupervisorPeriodEntriesMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Pobierz wpis po GID
 */
export type getEntryByGidResponse200 = {
	data: MonthlyEntryResponse;
	status: 200;
};

export type getEntryByGidResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type getEntryByGidResponseSuccess = getEntryByGidResponse200 & {
	headers: Headers;
};
export type getEntryByGidResponseError = getEntryByGidResponse404 & {
	headers: Headers;
};

export type getEntryByGidResponse =
	| getEntryByGidResponseSuccess
	| getEntryByGidResponseError;

export const getGetEntryByGidUrl = () => {
	return `/api/rcp/supervisor/entry`;
};

export const getEntryByGid = async (
	getByGidRequest: GetByGidRequest,
	options?: RequestInit,
): Promise<getEntryByGidResponse> => {
	return customFetch<getEntryByGidResponse>(getGetEntryByGidUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(getByGidRequest),
	});
};

export const getGetEntryByGidMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getEntryByGid>>,
		TError,
		{ data: GetByGidRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getEntryByGid>>,
	TError,
	{ data: GetByGidRequest },
	TContext
> => {
	const mutationKey = ["getEntryByGid"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getEntryByGid>>,
		{ data: GetByGidRequest }
	> = (props) => {
		const { data } = props ?? {};

		return getEntryByGid(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetEntryByGidMutationResult = NonNullable<
	Awaited<ReturnType<typeof getEntryByGid>>
>;
export type GetEntryByGidMutationBody = GetByGidRequest;
export type GetEntryByGidMutationError = ApiErrorResponse;

/**
 * @summary Pobierz wpis po GID
 */
export const useGetEntryByGid = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getEntryByGid>>,
			TError,
			{ data: GetByGidRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getEntryByGid>>,
	TError,
	{ data: GetByGidRequest },
	TContext
> => {
	const mutationOptions = getGetEntryByGidMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Zatwierdź wpis
 */
export type approveEntryResponse200 = {
	data: MonthlyEntryResponse;
	status: 200;
};

export type approveEntryResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type approveEntryResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type approveEntryResponseSuccess = approveEntryResponse200 & {
	headers: Headers;
};
export type approveEntryResponseError = (
	| approveEntryResponse400
	| approveEntryResponse404
) & {
	headers: Headers;
};

export type approveEntryResponse =
	| approveEntryResponseSuccess
	| approveEntryResponseError;

export const getApproveEntryUrl = (gid: string) => {
	return `/api/rcp/supervisor/${gid}/approve`;
};

export const approveEntry = async (
	gid: string,
	changeStatusRequest: ChangeStatusRequest,
	options?: RequestInit,
): Promise<approveEntryResponse> => {
	return customFetch<approveEntryResponse>(getApproveEntryUrl(gid), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(changeStatusRequest),
	});
};

export const getApproveEntryMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof approveEntry>>,
		TError,
		{ gid: string; data: ChangeStatusRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof approveEntry>>,
	TError,
	{ gid: string; data: ChangeStatusRequest },
	TContext
> => {
	const mutationKey = ["approveEntry"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof approveEntry>>,
		{ gid: string; data: ChangeStatusRequest }
	> = (props) => {
		const { gid, data } = props ?? {};

		return approveEntry(gid, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ApproveEntryMutationResult = NonNullable<
	Awaited<ReturnType<typeof approveEntry>>
>;
export type ApproveEntryMutationBody = ChangeStatusRequest;
export type ApproveEntryMutationError = ApiErrorResponse;

/**
 * @summary Zatwierdź wpis
 */
export const useApproveEntry = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof approveEntry>>,
			TError,
			{ gid: string; data: ChangeStatusRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof approveEntry>>,
	TError,
	{ gid: string; data: ChangeStatusRequest },
	TContext
> => {
	const mutationOptions = getApproveEntryMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Odrzuć wpis
 */
export type rejectEntryResponse200 = {
	data: MonthlyEntryResponse;
	status: 200;
};

export type rejectEntryResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type rejectEntryResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type rejectEntryResponseSuccess = rejectEntryResponse200 & {
	headers: Headers;
};
export type rejectEntryResponseError = (
	| rejectEntryResponse400
	| rejectEntryResponse404
) & {
	headers: Headers;
};

export type rejectEntryResponse =
	| rejectEntryResponseSuccess
	| rejectEntryResponseError;

export const getRejectEntryUrl = (gid: string) => {
	return `/api/rcp/supervisor/${gid}/reject`;
};

export const rejectEntry = async (
	gid: string,
	changeStatusRequest: ChangeStatusRequest,
	options?: RequestInit,
): Promise<rejectEntryResponse> => {
	return customFetch<rejectEntryResponse>(getRejectEntryUrl(gid), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(changeStatusRequest),
	});
};

export const getRejectEntryMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof rejectEntry>>,
		TError,
		{ gid: string; data: ChangeStatusRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof rejectEntry>>,
	TError,
	{ gid: string; data: ChangeStatusRequest },
	TContext
> => {
	const mutationKey = ["rejectEntry"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof rejectEntry>>,
		{ gid: string; data: ChangeStatusRequest }
	> = (props) => {
		const { gid, data } = props ?? {};

		return rejectEntry(gid, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type RejectEntryMutationResult = NonNullable<
	Awaited<ReturnType<typeof rejectEntry>>
>;
export type RejectEntryMutationBody = ChangeStatusRequest;
export type RejectEntryMutationError = ApiErrorResponse;

/**
 * @summary Odrzuć wpis
 */
export const useRejectEntry = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof rejectEntry>>,
			TError,
			{ gid: string; data: ChangeStatusRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof rejectEntry>>,
	TError,
	{ gid: string; data: ChangeStatusRequest },
	TContext
> => {
	const mutationOptions = getRejectEntryMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Przekaż do rozliczenia
 */
export type toSettlementResponse200 = {
	data: MonthlyEntryResponse;
	status: 200;
};

export type toSettlementResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type toSettlementResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type toSettlementResponseSuccess = toSettlementResponse200 & {
	headers: Headers;
};
export type toSettlementResponseError = (
	| toSettlementResponse400
	| toSettlementResponse404
) & {
	headers: Headers;
};

export type toSettlementResponse =
	| toSettlementResponseSuccess
	| toSettlementResponseError;

export const getToSettlementUrl = (gid: string) => {
	return `/api/rcp/supervisor/${gid}/to-settlement`;
};

export const toSettlement = async (
	gid: string,
	changeStatusRequest: ChangeStatusRequest,
	options?: RequestInit,
): Promise<toSettlementResponse> => {
	return customFetch<toSettlementResponse>(getToSettlementUrl(gid), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(changeStatusRequest),
	});
};

export const getToSettlementMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof toSettlement>>,
		TError,
		{ gid: string; data: ChangeStatusRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof toSettlement>>,
	TError,
	{ gid: string; data: ChangeStatusRequest },
	TContext
> => {
	const mutationKey = ["toSettlement"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof toSettlement>>,
		{ gid: string; data: ChangeStatusRequest }
	> = (props) => {
		const { gid, data } = props ?? {};

		return toSettlement(gid, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ToSettlementMutationResult = NonNullable<
	Awaited<ReturnType<typeof toSettlement>>
>;
export type ToSettlementMutationBody = ChangeStatusRequest;
export type ToSettlementMutationError = ApiErrorResponse;

/**
 * @summary Przekaż do rozliczenia
 */
export const useToSettlement = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof toSettlement>>,
			TError,
			{ gid: string; data: ChangeStatusRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof toSettlement>>,
	TError,
	{ gid: string; data: ChangeStatusRequest },
	TContext
> => {
	const mutationOptions = getToSettlementMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * Monitor subordinates' progress - shows all statuses
 * @summary Monitoruj postęp podwładnych
 */
export type getSupervisorMonitorPeriodResponse200 = {
	data: MonitorPeriodResponse;
	status: 200;
};

export type getSupervisorMonitorPeriodResponseSuccess =
	getSupervisorMonitorPeriodResponse200 & {
		headers: Headers;
	};

export type getSupervisorMonitorPeriodResponse =
	getSupervisorMonitorPeriodResponseSuccess;

export const getGetSupervisorMonitorPeriodUrl = () => {
	return `/api/rcp/supervisor/monitor/period`;
};

export const getSupervisorMonitorPeriod = async (
	getPeriodRequest: GetPeriodRequest,
	options?: RequestInit,
): Promise<getSupervisorMonitorPeriodResponse> => {
	return customFetch<getSupervisorMonitorPeriodResponse>(
		getGetSupervisorMonitorPeriodUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(getPeriodRequest),
		},
	);
};

export const getGetSupervisorMonitorPeriodMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getSupervisorMonitorPeriod>>,
		TError,
		{ data: GetPeriodRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getSupervisorMonitorPeriod>>,
	TError,
	{ data: GetPeriodRequest },
	TContext
> => {
	const mutationKey = ["getSupervisorMonitorPeriod"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getSupervisorMonitorPeriod>>,
		{ data: GetPeriodRequest }
	> = (props) => {
		const { data } = props ?? {};

		return getSupervisorMonitorPeriod(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetSupervisorMonitorPeriodMutationResult = NonNullable<
	Awaited<ReturnType<typeof getSupervisorMonitorPeriod>>
>;
export type GetSupervisorMonitorPeriodMutationBody = GetPeriodRequest;
export type GetSupervisorMonitorPeriodMutationError = unknown;

/**
 * @summary Monitoruj postęp podwładnych
 */
export const useGetSupervisorMonitorPeriod = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getSupervisorMonitorPeriod>>,
			TError,
			{ data: GetPeriodRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getSupervisorMonitorPeriod>>,
	TError,
	{ data: GetPeriodRequest },
	TContext
> => {
	const mutationOptions = getGetSupervisorMonitorPeriodMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * View subordinate's entry for monitoring
 * @summary Podgląd wpisu podwładnego
 */
export type getSupervisorMonitorEntryResponse200 = {
	data: MonthlyEntryResponse;
	status: 200;
};

export type getSupervisorMonitorEntryResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type getSupervisorMonitorEntryResponseSuccess =
	getSupervisorMonitorEntryResponse200 & {
		headers: Headers;
	};
export type getSupervisorMonitorEntryResponseError =
	getSupervisorMonitorEntryResponse404 & {
		headers: Headers;
	};

export type getSupervisorMonitorEntryResponse =
	| getSupervisorMonitorEntryResponseSuccess
	| getSupervisorMonitorEntryResponseError;

export const getGetSupervisorMonitorEntryUrl = () => {
	return `/api/rcp/supervisor/monitor/entry`;
};

export const getSupervisorMonitorEntry = async (
	getByGidRequest: GetByGidRequest,
	options?: RequestInit,
): Promise<getSupervisorMonitorEntryResponse> => {
	return customFetch<getSupervisorMonitorEntryResponse>(
		getGetSupervisorMonitorEntryUrl(),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(getByGidRequest),
		},
	);
};

export const getGetSupervisorMonitorEntryMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getSupervisorMonitorEntry>>,
		TError,
		{ data: GetByGidRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getSupervisorMonitorEntry>>,
	TError,
	{ data: GetByGidRequest },
	TContext
> => {
	const mutationKey = ["getSupervisorMonitorEntry"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getSupervisorMonitorEntry>>,
		{ data: GetByGidRequest }
	> = (props) => {
		const { data } = props ?? {};

		return getSupervisorMonitorEntry(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetSupervisorMonitorEntryMutationResult = NonNullable<
	Awaited<ReturnType<typeof getSupervisorMonitorEntry>>
>;
export type GetSupervisorMonitorEntryMutationBody = GetByGidRequest;
export type GetSupervisorMonitorEntryMutationError = ApiErrorResponse;

/**
 * @summary Podgląd wpisu podwładnego
 */
export const useGetSupervisorMonitorEntry = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getSupervisorMonitorEntry>>,
			TError,
			{ data: GetByGidRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getSupervisorMonitorEntry>>,
	TError,
	{ data: GetByGidRequest },
	TContext
> => {
	const mutationOptions = getGetSupervisorMonitorEntryMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
