/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Cdr API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type { ApiErrorResponse, CallStatusResponse } from "../../models";

import { customFetch } from "../../../custom-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Lista statusów połączeń
 */
export type getCallStatusesListResponse200 = {
	data: CallStatusResponse[];
	status: 200;
};

export type getCallStatusesListResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type getCallStatusesListResponseSuccess =
	getCallStatusesListResponse200 & {
		headers: Headers;
	};
export type getCallStatusesListResponseError =
	getCallStatusesListResponse400 & {
		headers: Headers;
	};

export type getCallStatusesListResponse =
	| getCallStatusesListResponseSuccess
	| getCallStatusesListResponseError;

export const getGetCallStatusesListUrl = () => {
	return `/api/cdr/call-statuses/list`;
};

export const getCallStatusesList = async (
	options?: RequestInit,
): Promise<getCallStatusesListResponse> => {
	return customFetch<getCallStatusesListResponse>(getGetCallStatusesListUrl(), {
		...options,
		method: "POST",
	});
};

export const getGetCallStatusesListMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getCallStatusesList>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getCallStatusesList>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["getCallStatusesList"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getCallStatusesList>>,
		void
	> = () => {
		return getCallStatusesList(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetCallStatusesListMutationResult = NonNullable<
	Awaited<ReturnType<typeof getCallStatusesList>>
>;

export type GetCallStatusesListMutationError = ApiErrorResponse;

/**
 * @summary Lista statusów połączeń
 */
export const useGetCallStatusesList = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getCallStatusesList>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getCallStatusesList>>,
	TError,
	void,
	TContext
> => {
	const mutationOptions = getGetCallStatusesListMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Pobierz status połączenia
 */
export type getCallStatusByGidResponse200 = {
	data: CallStatusResponse;
	status: 200;
};

export type getCallStatusByGidResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type getCallStatusByGidResponseSuccess =
	getCallStatusByGidResponse200 & {
		headers: Headers;
	};
export type getCallStatusByGidResponseError = getCallStatusByGidResponse404 & {
	headers: Headers;
};

export type getCallStatusByGidResponse =
	| getCallStatusByGidResponseSuccess
	| getCallStatusByGidResponseError;

export const getGetCallStatusByGidUrl = (gid: string) => {
	return `/api/cdr/call-statuses/${gid}`;
};

export const getCallStatusByGid = async (
	gid: string,
	options?: RequestInit,
): Promise<getCallStatusByGidResponse> => {
	return customFetch<getCallStatusByGidResponse>(
		getGetCallStatusByGidUrl(gid),
		{
			...options,
			method: "GET",
		},
	);
};

export const getGetCallStatusByGidQueryKey = (gid?: string) => {
	return [`/api/cdr/call-statuses/${gid}`] as const;
};

export const getGetCallStatusByGidQueryOptions = <
	TData = Awaited<ReturnType<typeof getCallStatusByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCallStatusByGid>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetCallStatusByGidQueryKey(gid);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getCallStatusByGid>>
	> = ({ signal }) => getCallStatusByGid(gid, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!gid,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getCallStatusByGid>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCallStatusByGidQueryResult = NonNullable<
	Awaited<ReturnType<typeof getCallStatusByGid>>
>;
export type GetCallStatusByGidQueryError = ApiErrorResponse;

export function useGetCallStatusByGid<
	TData = Awaited<ReturnType<typeof getCallStatusByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCallStatusByGid>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getCallStatusByGid>>,
					TError,
					Awaited<ReturnType<typeof getCallStatusByGid>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCallStatusByGid<
	TData = Awaited<ReturnType<typeof getCallStatusByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCallStatusByGid>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getCallStatusByGid>>,
					TError,
					Awaited<ReturnType<typeof getCallStatusByGid>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCallStatusByGid<
	TData = Awaited<ReturnType<typeof getCallStatusByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCallStatusByGid>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Pobierz status połączenia
 */

export function useGetCallStatusByGid<
	TData = Awaited<ReturnType<typeof getCallStatusByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCallStatusByGid>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetCallStatusByGidQueryOptions(gid, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}
