/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Identity API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";

import type {
	ApiErrorResponse,
	CreateStructureRequest,
	GetAllStructureRequest,
	GetStructureByIdRequest,
	StructureListFilter,
	StructureResponse,
	StructureResponsePagedResult,
	UpdateStructureRequest,
} from "../../models";

import { customFetch } from "../../../custom-fetch";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
	T,
>() => T extends Y ? 1 : 2
	? A
	: B;

type WritableKeys<T> = {
	[P in keyof T]-?: IfEquals<
		{ [Q in P]: T[P] },
		{ -readonly [Q in P]: T[P] },
		P
	>;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
	k: infer I,
) => void
	? I
	: never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
	? {
			[P in keyof Writable<T>]: T[P] extends object
				? NonReadonly<NonNullable<T[P]>>
				: T[P];
		}
	: DistributeReadOnlyOverUnions<T>;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getStructureListResponse200 = {
	data: StructureResponsePagedResult;
	status: 200;
};

export type getStructureListResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type getStructureListResponseSuccess = getStructureListResponse200 & {
	headers: Headers;
};
export type getStructureListResponseError = getStructureListResponse400 & {
	headers: Headers;
};

export type getStructureListResponse =
	| getStructureListResponseSuccess
	| getStructureListResponseError;

export const getGetStructureListUrl = () => {
	return `/api/identity/structure/list`;
};

export const getStructureList = async (
	structureListFilter: NonReadonly<StructureListFilter>,
	options?: RequestInit,
): Promise<getStructureListResponse> => {
	return customFetch<getStructureListResponse>(getGetStructureListUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(structureListFilter),
	});
};

export const getGetStructureListMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getStructureList>>,
		TError,
		{ data: NonReadonly<StructureListFilter> },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getStructureList>>,
	TError,
	{ data: NonReadonly<StructureListFilter> },
	TContext
> => {
	const mutationKey = ["getStructureList"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getStructureList>>,
		{ data: NonReadonly<StructureListFilter> }
	> = (props) => {
		const { data } = props ?? {};

		return getStructureList(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetStructureListMutationResult = NonNullable<
	Awaited<ReturnType<typeof getStructureList>>
>;
export type GetStructureListMutationBody = NonReadonly<StructureListFilter>;
export type GetStructureListMutationError = ApiErrorResponse;

export const useGetStructureList = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getStructureList>>,
			TError,
			{ data: NonReadonly<StructureListFilter> },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getStructureList>>,
	TError,
	{ data: NonReadonly<StructureListFilter> },
	TContext
> => {
	const mutationOptions = getGetStructureListMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
export type getAllStructureResponse200 = {
	data: StructureResponse[];
	status: 200;
};

export type getAllStructureResponseSuccess = getAllStructureResponse200 & {
	headers: Headers;
};

export type getAllStructureResponse = getAllStructureResponseSuccess;

export const getGetAllStructureUrl = () => {
	return `/api/identity/structure/all`;
};

export const getAllStructure = async (
	getAllStructureRequest: GetAllStructureRequest,
	options?: RequestInit,
): Promise<getAllStructureResponse> => {
	return customFetch<getAllStructureResponse>(getGetAllStructureUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(getAllStructureRequest),
	});
};

export const getGetAllStructureMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getAllStructure>>,
		TError,
		{ data: GetAllStructureRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getAllStructure>>,
	TError,
	{ data: GetAllStructureRequest },
	TContext
> => {
	const mutationKey = ["getAllStructure"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getAllStructure>>,
		{ data: GetAllStructureRequest }
	> = (props) => {
		const { data } = props ?? {};

		return getAllStructure(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetAllStructureMutationResult = NonNullable<
	Awaited<ReturnType<typeof getAllStructure>>
>;
export type GetAllStructureMutationBody = GetAllStructureRequest;
export type GetAllStructureMutationError = unknown;

export const useGetAllStructure = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getAllStructure>>,
			TError,
			{ data: GetAllStructureRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getAllStructure>>,
	TError,
	{ data: GetAllStructureRequest },
	TContext
> => {
	const mutationOptions = getGetAllStructureMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
export type getStructureResponse200 = {
	data: StructureResponse;
	status: 200;
};

export type getStructureResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type getStructureResponseSuccess = getStructureResponse200 & {
	headers: Headers;
};
export type getStructureResponseError = getStructureResponse404 & {
	headers: Headers;
};

export type getStructureResponse =
	| getStructureResponseSuccess
	| getStructureResponseError;

export const getGetStructureUrl = () => {
	return `/api/identity/structure/by-id`;
};

export const getStructure = async (
	getStructureByIdRequest: GetStructureByIdRequest,
	options?: RequestInit,
): Promise<getStructureResponse> => {
	return customFetch<getStructureResponse>(getGetStructureUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(getStructureByIdRequest),
	});
};

export const getGetStructureMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getStructure>>,
		TError,
		{ data: GetStructureByIdRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getStructure>>,
	TError,
	{ data: GetStructureByIdRequest },
	TContext
> => {
	const mutationKey = ["getStructure"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getStructure>>,
		{ data: GetStructureByIdRequest }
	> = (props) => {
		const { data } = props ?? {};

		return getStructure(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetStructureMutationResult = NonNullable<
	Awaited<ReturnType<typeof getStructure>>
>;
export type GetStructureMutationBody = GetStructureByIdRequest;
export type GetStructureMutationError = ApiErrorResponse;

export const useGetStructure = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getStructure>>,
			TError,
			{ data: GetStructureByIdRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getStructure>>,
	TError,
	{ data: GetStructureByIdRequest },
	TContext
> => {
	const mutationOptions = getGetStructureMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
export type createStructureResponse201 = {
	data: StructureResponse;
	status: 201;
};

export type createStructureResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type createStructureResponseSuccess = createStructureResponse201 & {
	headers: Headers;
};
export type createStructureResponseError = createStructureResponse400 & {
	headers: Headers;
};

export type createStructureResponse =
	| createStructureResponseSuccess
	| createStructureResponseError;

export const getCreateStructureUrl = () => {
	return `/api/identity/structure`;
};

export const createStructure = async (
	createStructureRequest: CreateStructureRequest,
	options?: RequestInit,
): Promise<createStructureResponse> => {
	return customFetch<createStructureResponse>(getCreateStructureUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(createStructureRequest),
	});
};

export const getCreateStructureMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createStructure>>,
		TError,
		{ data: CreateStructureRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createStructure>>,
	TError,
	{ data: CreateStructureRequest },
	TContext
> => {
	const mutationKey = ["createStructure"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createStructure>>,
		{ data: CreateStructureRequest }
	> = (props) => {
		const { data } = props ?? {};

		return createStructure(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateStructureMutationResult = NonNullable<
	Awaited<ReturnType<typeof createStructure>>
>;
export type CreateStructureMutationBody = CreateStructureRequest;
export type CreateStructureMutationError = ApiErrorResponse;

export const useCreateStructure = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createStructure>>,
			TError,
			{ data: CreateStructureRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createStructure>>,
	TError,
	{ data: CreateStructureRequest },
	TContext
> => {
	const mutationOptions = getCreateStructureMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
export type updateStructureResponse200 = {
	data: StructureResponse;
	status: 200;
};

export type updateStructureResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type updateStructureResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type updateStructureResponseSuccess = updateStructureResponse200 & {
	headers: Headers;
};
export type updateStructureResponseError = (
	| updateStructureResponse400
	| updateStructureResponse404
) & {
	headers: Headers;
};

export type updateStructureResponse =
	| updateStructureResponseSuccess
	| updateStructureResponseError;

export const getUpdateStructureUrl = (id: number) => {
	return `/api/identity/structure/${id}`;
};

export const updateStructure = async (
	id: number,
	updateStructureRequest: UpdateStructureRequest,
	options?: RequestInit,
): Promise<updateStructureResponse> => {
	return customFetch<updateStructureResponse>(getUpdateStructureUrl(id), {
		...options,
		method: "PUT",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(updateStructureRequest),
	});
};

export const getUpdateStructureMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateStructure>>,
		TError,
		{ id: number; data: UpdateStructureRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateStructure>>,
	TError,
	{ id: number; data: UpdateStructureRequest },
	TContext
> => {
	const mutationKey = ["updateStructure"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateStructure>>,
		{ id: number; data: UpdateStructureRequest }
	> = (props) => {
		const { id, data } = props ?? {};

		return updateStructure(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateStructureMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateStructure>>
>;
export type UpdateStructureMutationBody = UpdateStructureRequest;
export type UpdateStructureMutationError = ApiErrorResponse;

export const useUpdateStructure = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateStructure>>,
			TError,
			{ id: number; data: UpdateStructureRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateStructure>>,
	TError,
	{ id: number; data: UpdateStructureRequest },
	TContext
> => {
	const mutationOptions = getUpdateStructureMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
