/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Cdr API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface CallRecordListFilter {
	pageNumber?: number;
	pageSize?: number;
	/** @nullable */
	search?: string | null;
	/** @nullable */
	startDateFrom?: string | null;
	/** @nullable */
	startDateTo?: string | null;
	/** @nullable */
	callStatusId?: number | null;
	/** @nullable */
	callDirectionId?: number | null;
	/** @nullable */
	customerGid?: string | null;
	/** @nullable */
	sipAccountGid?: string | null;
	/** @nullable */
	minCost?: number | null;
	/** @nullable */
	maxCost?: number | null;
}
