/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Cdr API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface CallRecordDetailResponse {
	/** @nullable */
	gid?: string | null;
	/** @nullable */
	callerId?: string | null;
	/** @nullable */
	calledNumber?: string | null;
	startTime?: string;
	endTime?: string;
	duration?: number;
	billableSeconds?: number;
	/** @nullable */
	callStatusCode?: string | null;
	/** @nullable */
	callStatusName?: string | null;
	/** @nullable */
	callDirectionCode?: string | null;
	totalCost?: number;
	/** @nullable */
	currencyCode?: string | null;
	/** @nullable */
	customerName?: string | null;
	createdAt?: string;
	/** @nullable */
	callUuid?: string | null;
	/** @nullable */
	answerTime?: string | null;
	/** @nullable */
	terminationCauseCode?: string | null;
	/** @nullable */
	terminationCauseName?: string | null;
	/** @nullable */
	sourceGatewayGid?: string | null;
	/** @nullable */
	sourceGatewayName?: string | null;
	/** @nullable */
	destinationGatewayGid?: string | null;
	/** @nullable */
	destinationGatewayName?: string | null;
	/** @nullable */
	tariffGid?: string | null;
	/** @nullable */
	tariffName?: string | null;
	ratePerMinute?: number;
	connectionFee?: number;
	billingIncrement?: number;
	/** @nullable */
	destinationName?: string | null;
	/** @nullable */
	matchedPrefix?: string | null;
	/** @nullable */
	customerGid?: string | null;
	/** @nullable */
	sipAccountGid?: string | null;
	/** @nullable */
	sipAccountUsername?: string | null;
	/** @nullable */
	userData?: string | null;
}
