/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Cdr API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { CallRecordResponse } from "./callRecordResponse";

export interface CallRecordResponsePagedResult {
	/** @nullable */
	items?: CallRecordResponse[] | null;
	totalCount?: number;
	pageNumber?: number;
	pageSize?: number;
	readonly totalPages?: number;
	readonly hasPreviousPage?: boolean;
	readonly hasNextPage?: boolean;
}
