/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Cdr API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export * from "./apiErrorResponse";
export * from "./callDirectionResponse";
export * from "./callRecordDetailResponse";
export * from "./callRecordListFilter";
export * from "./callRecordResponse";
export * from "./callRecordResponsePagedResult";
export * from "./callStatusResponse";
export * from "./createCallRecordRequest";
export * from "./terminationCauseResponse";
export * from "./updateCallRecordRequest";
