/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Cdr API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface TerminationCauseResponse {
	/** @nullable */
	gid?: string | null;
	/** @nullable */
	code?: string | null;
	/** @nullable */
	q850Code?: number | null;
	/** @nullable */
	namePL?: string | null;
	/** @nullable */
	nameEN?: string | null;
	/** @nullable */
	description?: string | null;
	sortOrder?: number;
}
