/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Cdr API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface UpdateCallRecordRequest {
	/** @nullable */
	answerTime?: string | null;
	endTime?: string;
	duration?: number;
	billableSeconds?: number;
	callStatusId?: number;
	terminationCauseId?: number;
	totalCost?: number;
	/** @nullable */
	userData?: string | null;
}
