/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Identity API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { AppUserResponse } from "./appUserResponse";

export interface AppUserResponsePagedResult {
	/** @nullable */
	items?: AppUserResponse[] | null;
	totalCount?: number;
	pageNumber?: number;
	pageSize?: number;
	readonly totalPages?: number;
	readonly hasPreviousPage?: boolean;
	readonly hasNextPage?: boolean;
}
