/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Identity API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface ChangePasswordRequest {
	/** @nullable */
	newPassword?: string | null;
}
