/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Identity API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { Department } from "./department";

export interface CreateAppUserRequest {
	/** @nullable */
	firstName?: string | null;
	/** @nullable */
	lastName?: string | null;
	/** @nullable */
	email?: string | null;
	/** @nullable */
	password?: string | null;
	department?: Department;
	structureId?: number;
	/** @nullable */
	teamId?: number | null;
	/** @nullable */
	roles?: string[] | null;
}
