/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Identity API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface JdPrefillResponse {
	salesId?: number;
	/** @nullable */
	salesGid?: string | null;
	/** @nullable */
	salesName?: string | null;
	structureId?: number;
	/** @nullable */
	sbuName?: string | null;
	/** @nullable */
	teamId?: number | null;
	/** @nullable */
	teamGid?: string | null;
	/** @nullable */
	teamName?: string | null;
}
