/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Identity API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { AppRole } from "./appRole";

export interface MeResponse {
	/** @nullable */
	gid?: string | null;
	/** @nullable */
	email?: string | null;
	/** @nullable */
	firstName?: string | null;
	/** @nullable */
	lastName?: string | null;
	/** @nullable */
	roles?: AppRole[] | null;
	isActive?: boolean;
	structureId?: number;
	/** @nullable */
	teamId?: number | null;
}
