/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Identity API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface SetSupervisorRequest {
	/** @nullable */
	supervisorId?: number | null;
}
