/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Identity API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export type StructureRegion =
	(typeof StructureRegion)[keyof typeof StructureRegion];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StructureRegion = {
	Poland: "Poland",
	Foreign: "Foreign",
} as const;
