/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Identity API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { StructureRegion } from "./structureRegion";

export interface StructureListFilter {
	pageNumber?: number;
	pageSize?: number;
	readonly skip?: number;
	/** @nullable */
	search?: string | null;
	region?: StructureRegion;
	/** @nullable */
	isActive?: boolean | null;
}
