/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Identity API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export type TeamType = (typeof TeamType)[keyof typeof TeamType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TeamType = {
	IT: "IT",
	Support: "Support",
	Operations: "Operations",
	Sales: "Sales",
} as const;
