/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Identity API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface UpdateTeamRequest {
	structureId?: number;
	/** @nullable */
	code?: string | null;
	/** @nullable */
	name?: string | null;
	isActive?: boolean;
}
