/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rcp API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";

import type {
	ApiErrorResponse,
	DayEntryResponse,
	GetPeriodRequest,
	MonthlyEntryResponse,
	SaveDayEntryRequest,
	SubmitRequest,
} from "../../models";

import { customFetch } from "../../../custom-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Zapisz wpis dzienny
 */
export type saveDayEntryResponse200 = {
	data: DayEntryResponse;
	status: 200;
};

export type saveDayEntryResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type saveDayEntryResponseSuccess = saveDayEntryResponse200 & {
	headers: Headers;
};
export type saveDayEntryResponseError = saveDayEntryResponse400 & {
	headers: Headers;
};

export type saveDayEntryResponse =
	| saveDayEntryResponseSuccess
	| saveDayEntryResponseError;

export const getSaveDayEntryUrl = () => {
	return `/api/rcp/entry`;
};

export const saveDayEntry = async (
	saveDayEntryRequest: SaveDayEntryRequest,
	options?: RequestInit,
): Promise<saveDayEntryResponse> => {
	return customFetch<saveDayEntryResponse>(getSaveDayEntryUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(saveDayEntryRequest),
	});
};

export const getSaveDayEntryMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof saveDayEntry>>,
		TError,
		{ data: SaveDayEntryRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof saveDayEntry>>,
	TError,
	{ data: SaveDayEntryRequest },
	TContext
> => {
	const mutationKey = ["saveDayEntry"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof saveDayEntry>>,
		{ data: SaveDayEntryRequest }
	> = (props) => {
		const { data } = props ?? {};

		return saveDayEntry(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type SaveDayEntryMutationResult = NonNullable<
	Awaited<ReturnType<typeof saveDayEntry>>
>;
export type SaveDayEntryMutationBody = SaveDayEntryRequest;
export type SaveDayEntryMutationError = ApiErrorResponse;

/**
 * @summary Zapisz wpis dzienny
 */
export const useSaveDayEntry = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof saveDayEntry>>,
			TError,
			{ data: SaveDayEntryRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof saveDayEntry>>,
	TError,
	{ data: SaveDayEntryRequest },
	TContext
> => {
	const mutationOptions = getSaveDayEntryMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Usuń wpis dzienny
 */
export type deleteDayEntryResponse200 = {
	data: boolean;
	status: 200;
};

export type deleteDayEntryResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type deleteDayEntryResponseSuccess = deleteDayEntryResponse200 & {
	headers: Headers;
};
export type deleteDayEntryResponseError = deleteDayEntryResponse400 & {
	headers: Headers;
};

export type deleteDayEntryResponse =
	| deleteDayEntryResponseSuccess
	| deleteDayEntryResponseError;

export const getDeleteDayEntryUrl = (
	year: number,
	month: number,
	date: string,
) => {
	return `/api/rcp/entry/${year}/${month}/${date}`;
};

export const deleteDayEntry = async (
	year: number,
	month: number,
	date: string,
	options?: RequestInit,
): Promise<deleteDayEntryResponse> => {
	return customFetch<deleteDayEntryResponse>(
		getDeleteDayEntryUrl(year, month, date),
		{
			...options,
			method: "DELETE",
		},
	);
};

export const getDeleteDayEntryMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteDayEntry>>,
		TError,
		{ year: number; month: number; date: string },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteDayEntry>>,
	TError,
	{ year: number; month: number; date: string },
	TContext
> => {
	const mutationKey = ["deleteDayEntry"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteDayEntry>>,
		{ year: number; month: number; date: string }
	> = (props) => {
		const { year, month, date } = props ?? {};

		return deleteDayEntry(year, month, date, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteDayEntryMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteDayEntry>>
>;

export type DeleteDayEntryMutationError = ApiErrorResponse;

/**
 * @summary Usuń wpis dzienny
 */
export const useDeleteDayEntry = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteDayEntry>>,
			TError,
			{ year: number; month: number; date: string },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteDayEntry>>,
	TError,
	{ year: number; month: number; date: string },
	TContext
> => {
	const mutationOptions = getDeleteDayEntryMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Pobierz mój wpis miesięczny
 */
export type getMyMonthlyEntryResponse200 = {
	data: MonthlyEntryResponse;
	status: 200;
};

export type getMyMonthlyEntryResponseSuccess = getMyMonthlyEntryResponse200 & {
	headers: Headers;
};

export type getMyMonthlyEntryResponse = getMyMonthlyEntryResponseSuccess;

export const getGetMyMonthlyEntryUrl = () => {
	return `/api/rcp/my`;
};

export const getMyMonthlyEntry = async (
	getPeriodRequest: GetPeriodRequest,
	options?: RequestInit,
): Promise<getMyMonthlyEntryResponse> => {
	return customFetch<getMyMonthlyEntryResponse>(getGetMyMonthlyEntryUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(getPeriodRequest),
	});
};

export const getGetMyMonthlyEntryMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getMyMonthlyEntry>>,
		TError,
		{ data: GetPeriodRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getMyMonthlyEntry>>,
	TError,
	{ data: GetPeriodRequest },
	TContext
> => {
	const mutationKey = ["getMyMonthlyEntry"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getMyMonthlyEntry>>,
		{ data: GetPeriodRequest }
	> = (props) => {
		const { data } = props ?? {};

		return getMyMonthlyEntry(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetMyMonthlyEntryMutationResult = NonNullable<
	Awaited<ReturnType<typeof getMyMonthlyEntry>>
>;
export type GetMyMonthlyEntryMutationBody = GetPeriodRequest;
export type GetMyMonthlyEntryMutationError = unknown;

/**
 * @summary Pobierz mój wpis miesięczny
 */
export const useGetMyMonthlyEntry = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getMyMonthlyEntry>>,
			TError,
			{ data: GetPeriodRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getMyMonthlyEntry>>,
	TError,
	{ data: GetPeriodRequest },
	TContext
> => {
	const mutationOptions = getGetMyMonthlyEntryMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Wyślij do zatwierdzenia
 */
export type submitEntryResponse200 = {
	data: MonthlyEntryResponse;
	status: 200;
};

export type submitEntryResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type submitEntryResponseSuccess = submitEntryResponse200 & {
	headers: Headers;
};
export type submitEntryResponseError = submitEntryResponse400 & {
	headers: Headers;
};

export type submitEntryResponse =
	| submitEntryResponseSuccess
	| submitEntryResponseError;

export const getSubmitEntryUrl = () => {
	return `/api/rcp/my/submit`;
};

export const submitEntry = async (
	submitRequest: SubmitRequest,
	options?: RequestInit,
): Promise<submitEntryResponse> => {
	return customFetch<submitEntryResponse>(getSubmitEntryUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(submitRequest),
	});
};

export const getSubmitEntryMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof submitEntry>>,
		TError,
		{ data: SubmitRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof submitEntry>>,
	TError,
	{ data: SubmitRequest },
	TContext
> => {
	const mutationKey = ["submitEntry"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof submitEntry>>,
		{ data: SubmitRequest }
	> = (props) => {
		const { data } = props ?? {};

		return submitEntry(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type SubmitEntryMutationResult = NonNullable<
	Awaited<ReturnType<typeof submitEntry>>
>;
export type SubmitEntryMutationBody = SubmitRequest;
export type SubmitEntryMutationError = ApiErrorResponse;

/**
 * @summary Wyślij do zatwierdzenia
 */
export const useSubmitEntry = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof submitEntry>>,
			TError,
			{ data: SubmitRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof submitEntry>>,
	TError,
	{ data: SubmitRequest },
	TContext
> => {
	const mutationOptions = getSubmitEntryMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
