/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rcp API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface CommentResponse {
	/** @nullable */
	gid?: string | null;
	/** @nullable */
	content?: string | null;
	/** @nullable */
	authorName?: string | null;
	/** @nullable */
	authorRole?: string | null;
	createdAt?: string;
}
