/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rcp API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { MonitorEntrySummary } from "./monitorEntrySummary";

export interface MonitorPeriodResponse {
	year?: number;
	month?: number;
	workingDaysInMonth?: number;
	/** @nullable */
	entries?: MonitorEntrySummary[] | null;
}
