/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rcp API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { RcpTimeEntryStatus } from "./rcpTimeEntryStatus";
import type { DayEntryResponse } from "./dayEntryResponse";
import type { CommentResponse } from "./commentResponse";

export interface MonthlyEntryResponse {
	/** @nullable */
	gid?: string | null;
	year?: number;
	month?: number;
	status?: RcpTimeEntryStatus;
	totalMinutes?: number;
	/** @nullable */
	totalFormatted?: string | null;
	totalDecimalHours?: number;
	/** @nullable */
	employeeFullName?: string | null;
	/** @nullable */
	userGid?: string | null;
	/** @nullable */
	submittedAt?: string | null;
	/** @nullable */
	approvedAt?: string | null;
	/** @nullable */
	approvedByFullName?: string | null;
	/** @nullable */
	days?: DayEntryResponse[] | null;
	/** @nullable */
	comments?: CommentResponse[] | null;
}
