/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rcp API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { MonthlyEntrySummaryResponse } from "./monthlyEntrySummaryResponse";

export interface PeriodSummaryResponse {
	year?: number;
	month?: number;
	/** @nullable */
	entries?: MonthlyEntrySummaryResponse[] | null;
}
