/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rcp API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface SubmitRequest {
	year?: number;
	month?: number;
	/** @nullable */
	comment?: string | null;
}
