// <auto-generated />
using System;
using AnswerRule.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnswerRule.Data.Migrations
{
    [DbContext(typeof(AnswerRuleDbContext))]
    [Migration("20260204121049_Initial mig")]
    partial class Initialmig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnswerRule.Data.Entities.AnsweringRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("ActionTarget")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("action_target");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("gid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<long?>("ModifiedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("NotificationEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("notification_email");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<bool>("SendEmailNotification")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("send_email_notification");

                    b.Property<string>("SipAccountGid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("sip_account_gid");

                    b.Property<string>("VoiceMessageGid")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("voice_message_gid");

                    b.Property<string>("VoicemailBoxGid")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("voicemail_box_gid");

                    b.HasKey("Id");

                    b.HasIndex("Gid")
                        .IsUnique();

                    b.HasIndex("SipAccountGid");

                    b.HasIndex("IsEnabled", "Priority");

                    b.ToTable("answering_rules", (string)null);
                });

            modelBuilder.Entity("AnswerRule.Data.Entities.AnsweringRuleTimeSlot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("AnsweringRuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("answering_rule_id");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("day_of_week");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("gid");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_all_day");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("AnsweringRuleId");

                    b.HasIndex("Gid")
                        .IsUnique();

                    b.ToTable("answering_rule_time_slots", (string)null);
                });

            modelBuilder.Entity("AnswerRule.Data.Entities.AnsweringRuleTimeSlot", b =>
                {
                    b.HasOne("AnswerRule.Data.Entities.AnsweringRule", "AnsweringRule")
                        .WithMany("TimeSlots")
                        .HasForeignKey("AnsweringRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnsweringRule");
                });

            modelBuilder.Entity("AnswerRule.Data.Entities.AnsweringRule", b =>
                {
                    b.Navigation("TimeSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
