/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Identity API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";

import type {
	ApiErrorResponse,
	AppUserListFilter,
	AppUserResponse,
	AppUserResponsePagedResult,
	ChangePasswordRequest,
	CreateAppUserRequest,
	GetByGidRequest,
	SetSupervisorRequest,
	UpdateAppUserRequest,
} from "../../models";

import { customFetch } from "../../../custom-fetch";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
	T,
>() => T extends Y ? 1 : 2
	? A
	: B;

type WritableKeys<T> = {
	[P in keyof T]-?: IfEquals<
		{ [Q in P]: T[P] },
		{ -readonly [Q in P]: T[P] },
		P
	>;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
	k: infer I,
) => void
	? I
	: never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
	? {
			[P in keyof Writable<T>]: T[P] extends object
				? NonReadonly<NonNullable<T[P]>>
				: T[P];
		}
	: DistributeReadOnlyOverUnions<T>;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getAppUserListResponse200 = {
	data: AppUserResponsePagedResult;
	status: 200;
};

export type getAppUserListResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type getAppUserListResponseSuccess = getAppUserListResponse200 & {
	headers: Headers;
};
export type getAppUserListResponseError = getAppUserListResponse400 & {
	headers: Headers;
};

export type getAppUserListResponse =
	| getAppUserListResponseSuccess
	| getAppUserListResponseError;

export const getGetAppUserListUrl = () => {
	return `/api/identity/app-users/list`;
};

export const getAppUserList = async (
	appUserListFilter: NonReadonly<AppUserListFilter>,
	options?: RequestInit,
): Promise<getAppUserListResponse> => {
	return customFetch<getAppUserListResponse>(getGetAppUserListUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(appUserListFilter),
	});
};

export const getGetAppUserListMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getAppUserList>>,
		TError,
		{ data: NonReadonly<AppUserListFilter> },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getAppUserList>>,
	TError,
	{ data: NonReadonly<AppUserListFilter> },
	TContext
> => {
	const mutationKey = ["getAppUserList"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getAppUserList>>,
		{ data: NonReadonly<AppUserListFilter> }
	> = (props) => {
		const { data } = props ?? {};

		return getAppUserList(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetAppUserListMutationResult = NonNullable<
	Awaited<ReturnType<typeof getAppUserList>>
>;
export type GetAppUserListMutationBody = NonReadonly<AppUserListFilter>;
export type GetAppUserListMutationError = ApiErrorResponse;

export const useGetAppUserList = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getAppUserList>>,
			TError,
			{ data: NonReadonly<AppUserListFilter> },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getAppUserList>>,
	TError,
	{ data: NonReadonly<AppUserListFilter> },
	TContext
> => {
	const mutationOptions = getGetAppUserListMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
export type getAppUserResponse200 = {
	data: AppUserResponse;
	status: 200;
};

export type getAppUserResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type getAppUserResponseSuccess = getAppUserResponse200 & {
	headers: Headers;
};
export type getAppUserResponseError = getAppUserResponse404 & {
	headers: Headers;
};

export type getAppUserResponse =
	| getAppUserResponseSuccess
	| getAppUserResponseError;

export const getGetAppUserUrl = () => {
	return `/api/identity/app-users/by-gid`;
};

export const getAppUser = async (
	getByGidRequest: GetByGidRequest,
	options?: RequestInit,
): Promise<getAppUserResponse> => {
	return customFetch<getAppUserResponse>(getGetAppUserUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(getByGidRequest),
	});
};

export const getGetAppUserMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getAppUser>>,
		TError,
		{ data: GetByGidRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getAppUser>>,
	TError,
	{ data: GetByGidRequest },
	TContext
> => {
	const mutationKey = ["getAppUser"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getAppUser>>,
		{ data: GetByGidRequest }
	> = (props) => {
		const { data } = props ?? {};

		return getAppUser(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetAppUserMutationResult = NonNullable<
	Awaited<ReturnType<typeof getAppUser>>
>;
export type GetAppUserMutationBody = GetByGidRequest;
export type GetAppUserMutationError = ApiErrorResponse;

export const useGetAppUser = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getAppUser>>,
			TError,
			{ data: GetByGidRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getAppUser>>,
	TError,
	{ data: GetByGidRequest },
	TContext
> => {
	const mutationOptions = getGetAppUserMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
export type createAppUserResponse201 = {
	data: AppUserResponse;
	status: 201;
};

export type createAppUserResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type createAppUserResponseSuccess = createAppUserResponse201 & {
	headers: Headers;
};
export type createAppUserResponseError = createAppUserResponse400 & {
	headers: Headers;
};

export type createAppUserResponse =
	| createAppUserResponseSuccess
	| createAppUserResponseError;

export const getCreateAppUserUrl = () => {
	return `/api/identity/app-users`;
};

export const createAppUser = async (
	createAppUserRequest: CreateAppUserRequest,
	options?: RequestInit,
): Promise<createAppUserResponse> => {
	return customFetch<createAppUserResponse>(getCreateAppUserUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(createAppUserRequest),
	});
};

export const getCreateAppUserMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createAppUser>>,
		TError,
		{ data: CreateAppUserRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createAppUser>>,
	TError,
	{ data: CreateAppUserRequest },
	TContext
> => {
	const mutationKey = ["createAppUser"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createAppUser>>,
		{ data: CreateAppUserRequest }
	> = (props) => {
		const { data } = props ?? {};

		return createAppUser(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateAppUserMutationResult = NonNullable<
	Awaited<ReturnType<typeof createAppUser>>
>;
export type CreateAppUserMutationBody = CreateAppUserRequest;
export type CreateAppUserMutationError = ApiErrorResponse;

export const useCreateAppUser = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createAppUser>>,
			TError,
			{ data: CreateAppUserRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createAppUser>>,
	TError,
	{ data: CreateAppUserRequest },
	TContext
> => {
	const mutationOptions = getCreateAppUserMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
export type updateAppUserResponse200 = {
	data: AppUserResponse;
	status: 200;
};

export type updateAppUserResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type updateAppUserResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type updateAppUserResponseSuccess = updateAppUserResponse200 & {
	headers: Headers;
};
export type updateAppUserResponseError = (
	| updateAppUserResponse400
	| updateAppUserResponse404
) & {
	headers: Headers;
};

export type updateAppUserResponse =
	| updateAppUserResponseSuccess
	| updateAppUserResponseError;

export const getUpdateAppUserUrl = (gid: string) => {
	return `/api/identity/app-users/${gid}`;
};

export const updateAppUser = async (
	gid: string,
	updateAppUserRequest: UpdateAppUserRequest,
	options?: RequestInit,
): Promise<updateAppUserResponse> => {
	return customFetch<updateAppUserResponse>(getUpdateAppUserUrl(gid), {
		...options,
		method: "PUT",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(updateAppUserRequest),
	});
};

export const getUpdateAppUserMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateAppUser>>,
		TError,
		{ gid: string; data: UpdateAppUserRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateAppUser>>,
	TError,
	{ gid: string; data: UpdateAppUserRequest },
	TContext
> => {
	const mutationKey = ["updateAppUser"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateAppUser>>,
		{ gid: string; data: UpdateAppUserRequest }
	> = (props) => {
		const { gid, data } = props ?? {};

		return updateAppUser(gid, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateAppUserMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateAppUser>>
>;
export type UpdateAppUserMutationBody = UpdateAppUserRequest;
export type UpdateAppUserMutationError = ApiErrorResponse;

export const useUpdateAppUser = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateAppUser>>,
			TError,
			{ gid: string; data: UpdateAppUserRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateAppUser>>,
	TError,
	{ gid: string; data: UpdateAppUserRequest },
	TContext
> => {
	const mutationOptions = getUpdateAppUserMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
export type deleteAppUserResponse200 = {
	data: boolean;
	status: 200;
};

export type deleteAppUserResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type deleteAppUserResponseSuccess = deleteAppUserResponse200 & {
	headers: Headers;
};
export type deleteAppUserResponseError = deleteAppUserResponse404 & {
	headers: Headers;
};

export type deleteAppUserResponse =
	| deleteAppUserResponseSuccess
	| deleteAppUserResponseError;

export const getDeleteAppUserUrl = (gid: string) => {
	return `/api/identity/app-users/${gid}`;
};

export const deleteAppUser = async (
	gid: string,
	options?: RequestInit,
): Promise<deleteAppUserResponse> => {
	return customFetch<deleteAppUserResponse>(getDeleteAppUserUrl(gid), {
		...options,
		method: "DELETE",
	});
};

export const getDeleteAppUserMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteAppUser>>,
		TError,
		{ gid: string },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteAppUser>>,
	TError,
	{ gid: string },
	TContext
> => {
	const mutationKey = ["deleteAppUser"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteAppUser>>,
		{ gid: string }
	> = (props) => {
		const { gid } = props ?? {};

		return deleteAppUser(gid, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteAppUserMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteAppUser>>
>;

export type DeleteAppUserMutationError = ApiErrorResponse;

export const useDeleteAppUser = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteAppUser>>,
			TError,
			{ gid: string },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteAppUser>>,
	TError,
	{ gid: string },
	TContext
> => {
	const mutationOptions = getDeleteAppUserMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
export type changeAppUserPasswordResponse200 = {
	data: boolean;
	status: 200;
};

export type changeAppUserPasswordResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type changeAppUserPasswordResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type changeAppUserPasswordResponseSuccess =
	changeAppUserPasswordResponse200 & {
		headers: Headers;
	};
export type changeAppUserPasswordResponseError = (
	| changeAppUserPasswordResponse400
	| changeAppUserPasswordResponse404
) & {
	headers: Headers;
};

export type changeAppUserPasswordResponse =
	| changeAppUserPasswordResponseSuccess
	| changeAppUserPasswordResponseError;

export const getChangeAppUserPasswordUrl = (gid: string) => {
	return `/api/identity/app-users/${gid}/password`;
};

export const changeAppUserPassword = async (
	gid: string,
	changePasswordRequest: ChangePasswordRequest,
	options?: RequestInit,
): Promise<changeAppUserPasswordResponse> => {
	return customFetch<changeAppUserPasswordResponse>(
		getChangeAppUserPasswordUrl(gid),
		{
			...options,
			method: "PUT",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(changePasswordRequest),
		},
	);
};

export const getChangeAppUserPasswordMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof changeAppUserPassword>>,
		TError,
		{ gid: string; data: ChangePasswordRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof changeAppUserPassword>>,
	TError,
	{ gid: string; data: ChangePasswordRequest },
	TContext
> => {
	const mutationKey = ["changeAppUserPassword"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof changeAppUserPassword>>,
		{ gid: string; data: ChangePasswordRequest }
	> = (props) => {
		const { gid, data } = props ?? {};

		return changeAppUserPassword(gid, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ChangeAppUserPasswordMutationResult = NonNullable<
	Awaited<ReturnType<typeof changeAppUserPassword>>
>;
export type ChangeAppUserPasswordMutationBody = ChangePasswordRequest;
export type ChangeAppUserPasswordMutationError = ApiErrorResponse;

export const useChangeAppUserPassword = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof changeAppUserPassword>>,
			TError,
			{ gid: string; data: ChangePasswordRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof changeAppUserPassword>>,
	TError,
	{ gid: string; data: ChangePasswordRequest },
	TContext
> => {
	const mutationOptions = getChangeAppUserPasswordMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
export type setAppUserSupervisorResponse200 = {
	data: AppUserResponse;
	status: 200;
};

export type setAppUserSupervisorResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type setAppUserSupervisorResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type setAppUserSupervisorResponseSuccess =
	setAppUserSupervisorResponse200 & {
		headers: Headers;
	};
export type setAppUserSupervisorResponseError = (
	| setAppUserSupervisorResponse400
	| setAppUserSupervisorResponse404
) & {
	headers: Headers;
};

export type setAppUserSupervisorResponse =
	| setAppUserSupervisorResponseSuccess
	| setAppUserSupervisorResponseError;

export const getSetAppUserSupervisorUrl = (gid: string) => {
	return `/api/identity/app-users/${gid}/supervisor`;
};

export const setAppUserSupervisor = async (
	gid: string,
	setSupervisorRequest: SetSupervisorRequest,
	options?: RequestInit,
): Promise<setAppUserSupervisorResponse> => {
	return customFetch<setAppUserSupervisorResponse>(
		getSetAppUserSupervisorUrl(gid),
		{
			...options,
			method: "PUT",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(setSupervisorRequest),
		},
	);
};

export const getSetAppUserSupervisorMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof setAppUserSupervisor>>,
		TError,
		{ gid: string; data: SetSupervisorRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof setAppUserSupervisor>>,
	TError,
	{ gid: string; data: SetSupervisorRequest },
	TContext
> => {
	const mutationKey = ["setAppUserSupervisor"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof setAppUserSupervisor>>,
		{ gid: string; data: SetSupervisorRequest }
	> = (props) => {
		const { gid, data } = props ?? {};

		return setAppUserSupervisor(gid, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type SetAppUserSupervisorMutationResult = NonNullable<
	Awaited<ReturnType<typeof setAppUserSupervisor>>
>;
export type SetAppUserSupervisorMutationBody = SetSupervisorRequest;
export type SetAppUserSupervisorMutationError = ApiErrorResponse;

export const useSetAppUserSupervisor = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof setAppUserSupervisor>>,
			TError,
			{ gid: string; data: SetSupervisorRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof setAppUserSupervisor>>,
	TError,
	{ gid: string; data: SetSupervisorRequest },
	TContext
> => {
	const mutationOptions = getSetAppUserSupervisorMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
