/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rate API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type {
	ApiErrorResponse,
	CreateTariffRequest,
	TariffDetailResponse,
	TariffListFilter,
	TariffResponse,
	TariffResponsePagedResult,
	UpdateTariffRequest,
} from "../../models";

import { customFetch } from "../../../custom-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Lista taryf
 */
export type getTariffsListResponse200 = {
	data: TariffResponsePagedResult;
	status: 200;
};

export type getTariffsListResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type getTariffsListResponseSuccess = getTariffsListResponse200 & {
	headers: Headers;
};
export type getTariffsListResponseError = getTariffsListResponse400 & {
	headers: Headers;
};

export type getTariffsListResponse =
	| getTariffsListResponseSuccess
	| getTariffsListResponseError;

export const getGetTariffsListUrl = () => {
	return `/api/rate/tariffs/list`;
};

export const getTariffsList = async (
	tariffListFilter: TariffListFilter,
	options?: RequestInit,
): Promise<getTariffsListResponse> => {
	return customFetch<getTariffsListResponse>(getGetTariffsListUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(tariffListFilter),
	});
};

export const getGetTariffsListMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getTariffsList>>,
		TError,
		{ data: TariffListFilter },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getTariffsList>>,
	TError,
	{ data: TariffListFilter },
	TContext
> => {
	const mutationKey = ["getTariffsList"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getTariffsList>>,
		{ data: TariffListFilter }
	> = (props) => {
		const { data } = props ?? {};

		return getTariffsList(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetTariffsListMutationResult = NonNullable<
	Awaited<ReturnType<typeof getTariffsList>>
>;
export type GetTariffsListMutationBody = TariffListFilter;
export type GetTariffsListMutationError = ApiErrorResponse;

/**
 * @summary Lista taryf
 */
export const useGetTariffsList = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getTariffsList>>,
			TError,
			{ data: TariffListFilter },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getTariffsList>>,
	TError,
	{ data: TariffListFilter },
	TContext
> => {
	const mutationOptions = getGetTariffsListMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Pobierz taryfę
 */
export type getTariffByGidResponse200 = {
	data: TariffDetailResponse;
	status: 200;
};

export type getTariffByGidResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type getTariffByGidResponseSuccess = getTariffByGidResponse200 & {
	headers: Headers;
};
export type getTariffByGidResponseError = getTariffByGidResponse404 & {
	headers: Headers;
};

export type getTariffByGidResponse =
	| getTariffByGidResponseSuccess
	| getTariffByGidResponseError;

export const getGetTariffByGidUrl = (gid: string) => {
	return `/api/rate/tariffs/${gid}`;
};

export const getTariffByGid = async (
	gid: string,
	options?: RequestInit,
): Promise<getTariffByGidResponse> => {
	return customFetch<getTariffByGidResponse>(getGetTariffByGidUrl(gid), {
		...options,
		method: "GET",
	});
};

export const getGetTariffByGidQueryKey = (gid?: string) => {
	return [`/api/rate/tariffs/${gid}`] as const;
};

export const getGetTariffByGidQueryOptions = <
	TData = Awaited<ReturnType<typeof getTariffByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getTariffByGid>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetTariffByGidQueryKey(gid);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getTariffByGid>>> = ({
		signal,
	}) => getTariffByGid(gid, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!gid,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getTariffByGid>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTariffByGidQueryResult = NonNullable<
	Awaited<ReturnType<typeof getTariffByGid>>
>;
export type GetTariffByGidQueryError = ApiErrorResponse;

export function useGetTariffByGid<
	TData = Awaited<ReturnType<typeof getTariffByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getTariffByGid>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getTariffByGid>>,
					TError,
					Awaited<ReturnType<typeof getTariffByGid>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTariffByGid<
	TData = Awaited<ReturnType<typeof getTariffByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getTariffByGid>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getTariffByGid>>,
					TError,
					Awaited<ReturnType<typeof getTariffByGid>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTariffByGid<
	TData = Awaited<ReturnType<typeof getTariffByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getTariffByGid>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Pobierz taryfę
 */

export function useGetTariffByGid<
	TData = Awaited<ReturnType<typeof getTariffByGid>>,
	TError = ApiErrorResponse,
>(
	gid: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getTariffByGid>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetTariffByGidQueryOptions(gid, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * @summary Aktualizuj taryfę
 */
export type updateTariffResponse200 = {
	data: TariffResponse;
	status: 200;
};

export type updateTariffResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type updateTariffResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type updateTariffResponseSuccess = updateTariffResponse200 & {
	headers: Headers;
};
export type updateTariffResponseError = (
	| updateTariffResponse400
	| updateTariffResponse404
) & {
	headers: Headers;
};

export type updateTariffResponse =
	| updateTariffResponseSuccess
	| updateTariffResponseError;

export const getUpdateTariffUrl = (gid: string) => {
	return `/api/rate/tariffs/${gid}`;
};

export const updateTariff = async (
	gid: string,
	updateTariffRequest: UpdateTariffRequest,
	options?: RequestInit,
): Promise<updateTariffResponse> => {
	return customFetch<updateTariffResponse>(getUpdateTariffUrl(gid), {
		...options,
		method: "PUT",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(updateTariffRequest),
	});
};

export const getUpdateTariffMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateTariff>>,
		TError,
		{ gid: string; data: UpdateTariffRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateTariff>>,
	TError,
	{ gid: string; data: UpdateTariffRequest },
	TContext
> => {
	const mutationKey = ["updateTariff"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateTariff>>,
		{ gid: string; data: UpdateTariffRequest }
	> = (props) => {
		const { gid, data } = props ?? {};

		return updateTariff(gid, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateTariffMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateTariff>>
>;
export type UpdateTariffMutationBody = UpdateTariffRequest;
export type UpdateTariffMutationError = ApiErrorResponse;

/**
 * @summary Aktualizuj taryfę
 */
export const useUpdateTariff = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateTariff>>,
			TError,
			{ gid: string; data: UpdateTariffRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateTariff>>,
	TError,
	{ gid: string; data: UpdateTariffRequest },
	TContext
> => {
	const mutationOptions = getUpdateTariffMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Usuń taryfę
 */
export type deleteTariffResponse200 = {
	data: boolean;
	status: 200;
};

export type deleteTariffResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type deleteTariffResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type deleteTariffResponseSuccess = deleteTariffResponse200 & {
	headers: Headers;
};
export type deleteTariffResponseError = (
	| deleteTariffResponse400
	| deleteTariffResponse404
) & {
	headers: Headers;
};

export type deleteTariffResponse =
	| deleteTariffResponseSuccess
	| deleteTariffResponseError;

export const getDeleteTariffUrl = (gid: string) => {
	return `/api/rate/tariffs/${gid}`;
};

export const deleteTariff = async (
	gid: string,
	options?: RequestInit,
): Promise<deleteTariffResponse> => {
	return customFetch<deleteTariffResponse>(getDeleteTariffUrl(gid), {
		...options,
		method: "DELETE",
	});
};

export const getDeleteTariffMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteTariff>>,
		TError,
		{ gid: string },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteTariff>>,
	TError,
	{ gid: string },
	TContext
> => {
	const mutationKey = ["deleteTariff"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteTariff>>,
		{ gid: string }
	> = (props) => {
		const { gid } = props ?? {};

		return deleteTariff(gid, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteTariffMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteTariff>>
>;

export type DeleteTariffMutationError = ApiErrorResponse;

/**
 * @summary Usuń taryfę
 */
export const useDeleteTariff = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteTariff>>,
			TError,
			{ gid: string },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteTariff>>,
	TError,
	{ gid: string },
	TContext
> => {
	const mutationOptions = getDeleteTariffMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Utwórz taryfę
 */
export type createTariffResponse200 = {
	data: TariffResponse;
	status: 200;
};

export type createTariffResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type createTariffResponseSuccess = createTariffResponse200 & {
	headers: Headers;
};
export type createTariffResponseError = createTariffResponse400 & {
	headers: Headers;
};

export type createTariffResponse =
	| createTariffResponseSuccess
	| createTariffResponseError;

export const getCreateTariffUrl = () => {
	return `/api/rate/tariffs`;
};

export const createTariff = async (
	createTariffRequest: CreateTariffRequest,
	options?: RequestInit,
): Promise<createTariffResponse> => {
	return customFetch<createTariffResponse>(getCreateTariffUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(createTariffRequest),
	});
};

export const getCreateTariffMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createTariff>>,
		TError,
		{ data: CreateTariffRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createTariff>>,
	TError,
	{ data: CreateTariffRequest },
	TContext
> => {
	const mutationKey = ["createTariff"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createTariff>>,
		{ data: CreateTariffRequest }
	> = (props) => {
		const { data } = props ?? {};

		return createTariff(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateTariffMutationResult = NonNullable<
	Awaited<ReturnType<typeof createTariff>>
>;
export type CreateTariffMutationBody = CreateTariffRequest;
export type CreateTariffMutationError = ApiErrorResponse;

/**
 * @summary Utwórz taryfę
 */
export const useCreateTariff = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createTariff>>,
			TError,
			{ data: CreateTariffRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createTariff>>,
	TError,
	{ data: CreateTariffRequest },
	TContext
> => {
	const mutationOptions = getCreateTariffMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
