/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface ApiErrorResponse {
	/** @nullable */
	code?: string | null;
	/** @nullable */
	message?: string | null;
}
