/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */

export interface LoginRequest {
	/** @nullable */
	email?: string | null;
	/** @nullable */
	password?: string | null;
}
