/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Gateway API
 * OpenAPI spec version: v1
 */
import type { AppRole } from "./appRole";

export interface LoginResponse {
	/** @nullable */
	token?: string | null;
	/** @nullable */
	gid?: string | null;
	/** @nullable */
	email?: string | null;
	/** @nullable */
	firstName?: string | null;
	/** @nullable */
	lastName?: string | null;
	/** @nullable */
	roles?: AppRole[] | null;
	expiresAt?: string;
}
