/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX AnswerRule API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { AnsweringRuleAction } from "./answeringRuleAction";

export interface ActiveRuleInfo {
	/** @nullable */
	gid?: string | null;
	/** @nullable */
	name?: string | null;
	actionType?: AnsweringRuleAction;
	/** @nullable */
	actionTarget?: string | null;
	/** @nullable */
	voicemailBoxGid?: string | null;
	/** @nullable */
	voiceMessageGid?: string | null;
	sendEmailNotification?: boolean;
	/** @nullable */
	notificationEmail?: string | null;
}
