/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX AnswerRule API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { AnsweringRuleAction } from "./answeringRuleAction";
import type { TimeSlotDto } from "./timeSlotDto";

export interface AnsweringRuleDetailResponse {
	/** @nullable */
	gid?: string | null;
	/** @nullable */
	name?: string | null;
	/** @nullable */
	description?: string | null;
	priority?: number;
	isEnabled?: boolean;
	actionType?: AnsweringRuleAction;
	/** @nullable */
	actionTarget?: string | null;
	sendEmailNotification?: boolean;
	timeSlotsCount?: number;
	createdAt?: string;
	/** @nullable */
	sipAccountGid?: string | null;
	/** @nullable */
	voicemailBoxGid?: string | null;
	/** @nullable */
	voiceMessageGid?: string | null;
	/** @nullable */
	notificationEmail?: string | null;
	/** @nullable */
	timeSlots?: TimeSlotDto[] | null;
}
