/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX AnswerRule API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { AnsweringRuleResponse } from "./answeringRuleResponse";

export interface AnsweringRuleResponsePagedResult {
	/** @nullable */
	items?: AnsweringRuleResponse[] | null;
	totalCount?: number;
	pageNumber?: number;
	pageSize?: number;
	readonly totalPages?: number;
	readonly hasPreviousPage?: boolean;
	readonly hasNextPage?: boolean;
}
