/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX AnswerRule API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { AnsweringRuleAction } from "./answeringRuleAction";

export interface AnsweringRuleListFilter {
	pageNumber?: number;
	pageSize?: number;
	readonly skip?: number;
	/** @nullable */
	sipAccountGid?: string | null;
	/** @nullable */
	search?: string | null;
	/** @nullable */
	isEnabled?: boolean | null;
	actionType?: AnsweringRuleAction;
}
