/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX AnswerRule API (via Gateway)
 * OpenAPI spec version: 1.0
 */

export interface CheckRuleRequest {
	/** @nullable */
	sipAccountGid?: string | null;
	/** @nullable */
	checkDateTime?: string | null;
}
