/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX AnswerRule API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import type { ActiveRuleInfo } from "./activeRuleInfo";

export interface CheckRuleResponse {
	hasActiveRule?: boolean;
	rule?: ActiveRuleInfo;
}
