/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Rcp API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";

import type {
	ApiErrorResponse,
	CommentRequest,
	CommentResponse,
	GetByGidRequest,
} from "../../models";

import { customFetch } from "../../../custom-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Pobierz komentarze
 */
export type getCommentsResponse200 = {
	data: CommentResponse[];
	status: 200;
};

export type getCommentsResponseSuccess = getCommentsResponse200 & {
	headers: Headers;
};

export type getCommentsResponse = getCommentsResponseSuccess;

export const getGetCommentsUrl = () => {
	return `/api/rcp/comments/list`;
};

export const getComments = async (
	getByGidRequest: GetByGidRequest,
	options?: RequestInit,
): Promise<getCommentsResponse> => {
	return customFetch<getCommentsResponse>(getGetCommentsUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(getByGidRequest),
	});
};

export const getGetCommentsMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getComments>>,
		TError,
		{ data: GetByGidRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getComments>>,
	TError,
	{ data: GetByGidRequest },
	TContext
> => {
	const mutationKey = ["getComments"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getComments>>,
		{ data: GetByGidRequest }
	> = (props) => {
		const { data } = props ?? {};

		return getComments(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetCommentsMutationResult = NonNullable<
	Awaited<ReturnType<typeof getComments>>
>;
export type GetCommentsMutationBody = GetByGidRequest;
export type GetCommentsMutationError = unknown;

/**
 * @summary Pobierz komentarze
 */
export const useGetComments = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getComments>>,
			TError,
			{ data: GetByGidRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getComments>>,
	TError,
	{ data: GetByGidRequest },
	TContext
> => {
	const mutationOptions = getGetCommentsMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Dodaj komentarz
 */
export type addCommentResponse200 = {
	data: CommentResponse;
	status: 200;
};

export type addCommentResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type addCommentResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type addCommentResponseSuccess = addCommentResponse200 & {
	headers: Headers;
};
export type addCommentResponseError = (
	| addCommentResponse400
	| addCommentResponse404
) & {
	headers: Headers;
};

export type addCommentResponse =
	| addCommentResponseSuccess
	| addCommentResponseError;

export const getAddCommentUrl = (gid: string) => {
	return `/api/rcp/${gid}/comments`;
};

export const addComment = async (
	gid: string,
	commentRequest: CommentRequest,
	options?: RequestInit,
): Promise<addCommentResponse> => {
	return customFetch<addCommentResponse>(getAddCommentUrl(gid), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(commentRequest),
	});
};

export const getAddCommentMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof addComment>>,
		TError,
		{ gid: string; data: CommentRequest },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof addComment>>,
	TError,
	{ gid: string; data: CommentRequest },
	TContext
> => {
	const mutationKey = ["addComment"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof addComment>>,
		{ gid: string; data: CommentRequest }
	> = (props) => {
		const { gid, data } = props ?? {};

		return addComment(gid, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type AddCommentMutationResult = NonNullable<
	Awaited<ReturnType<typeof addComment>>
>;
export type AddCommentMutationBody = CommentRequest;
export type AddCommentMutationError = ApiErrorResponse;

/**
 * @summary Dodaj komentarz
 */
export const useAddComment = <TError = ApiErrorResponse, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof addComment>>,
			TError,
			{ gid: string; data: CommentRequest },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof addComment>>,
	TError,
	{ gid: string; data: CommentRequest },
	TContext
> => {
	const mutationOptions = getAddCommentMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
