/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * PBX Fincosts API (via Gateway)
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";

import type {
	ApiErrorResponse,
	CurrencyTypeResponse,
	DocumentEntryListFilter,
	DocumentEntryResponsePagedResult,
	DocumentTypeResponse,
	VatRateTypeResponse,
} from "../../models";

import { customFetch } from "../../../custom-fetch";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
	T,
>() => T extends Y ? 1 : 2
	? A
	: B;

type WritableKeys<T> = {
	[P in keyof T]-?: IfEquals<
		{ [Q in P]: T[P] },
		{ -readonly [Q in P]: T[P] },
		P
	>;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
	k: infer I,
) => void
	? I
	: never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
	? {
			[P in keyof Writable<T>]: T[P] extends object
				? NonReadonly<NonNullable<T[P]>>
				: T[P];
		}
	: DistributeReadOnlyOverUnions<T>;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getDocumentTypesResponse200 = {
	data: DocumentTypeResponse[];
	status: 200;
};

export type getDocumentTypesResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type getDocumentTypesResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type getDocumentTypesResponseSuccess = getDocumentTypesResponse200 & {
	headers: Headers;
};
export type getDocumentTypesResponseError = (
	| getDocumentTypesResponse400
	| getDocumentTypesResponse404
) & {
	headers: Headers;
};

export type getDocumentTypesResponse =
	| getDocumentTypesResponseSuccess
	| getDocumentTypesResponseError;

export const getGetDocumentTypesUrl = () => {
	return `/api/fincosts/costs/document-types`;
};

export const getDocumentTypes = async (
	options?: RequestInit,
): Promise<getDocumentTypesResponse> => {
	return customFetch<getDocumentTypesResponse>(getGetDocumentTypesUrl(), {
		...options,
		method: "POST",
	});
};

export const getGetDocumentTypesMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getDocumentTypes>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getDocumentTypes>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["getDocumentTypes"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getDocumentTypes>>,
		void
	> = () => {
		return getDocumentTypes(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetDocumentTypesMutationResult = NonNullable<
	Awaited<ReturnType<typeof getDocumentTypes>>
>;

export type GetDocumentTypesMutationError = ApiErrorResponse;

export const useGetDocumentTypes = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getDocumentTypes>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getDocumentTypes>>,
	TError,
	void,
	TContext
> => {
	const mutationOptions = getGetDocumentTypesMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
export type getCurrencyTypesResponse200 = {
	data: CurrencyTypeResponse[];
	status: 200;
};

export type getCurrencyTypesResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type getCurrencyTypesResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type getCurrencyTypesResponseSuccess = getCurrencyTypesResponse200 & {
	headers: Headers;
};
export type getCurrencyTypesResponseError = (
	| getCurrencyTypesResponse400
	| getCurrencyTypesResponse404
) & {
	headers: Headers;
};

export type getCurrencyTypesResponse =
	| getCurrencyTypesResponseSuccess
	| getCurrencyTypesResponseError;

export const getGetCurrencyTypesUrl = () => {
	return `/api/fincosts/costs/currency-types`;
};

export const getCurrencyTypes = async (
	options?: RequestInit,
): Promise<getCurrencyTypesResponse> => {
	return customFetch<getCurrencyTypesResponse>(getGetCurrencyTypesUrl(), {
		...options,
		method: "POST",
	});
};

export const getGetCurrencyTypesMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getCurrencyTypes>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getCurrencyTypes>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["getCurrencyTypes"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getCurrencyTypes>>,
		void
	> = () => {
		return getCurrencyTypes(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetCurrencyTypesMutationResult = NonNullable<
	Awaited<ReturnType<typeof getCurrencyTypes>>
>;

export type GetCurrencyTypesMutationError = ApiErrorResponse;

export const useGetCurrencyTypes = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getCurrencyTypes>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getCurrencyTypes>>,
	TError,
	void,
	TContext
> => {
	const mutationOptions = getGetCurrencyTypesMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
export type getVatRateTypesResponse200 = {
	data: VatRateTypeResponse[];
	status: 200;
};

export type getVatRateTypesResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type getVatRateTypesResponse404 = {
	data: ApiErrorResponse;
	status: 404;
};

export type getVatRateTypesResponseSuccess = getVatRateTypesResponse200 & {
	headers: Headers;
};
export type getVatRateTypesResponseError = (
	| getVatRateTypesResponse400
	| getVatRateTypesResponse404
) & {
	headers: Headers;
};

export type getVatRateTypesResponse =
	| getVatRateTypesResponseSuccess
	| getVatRateTypesResponseError;

export const getGetVatRateTypesUrl = () => {
	return `/api/fincosts/costs/vat-rate-types`;
};

export const getVatRateTypes = async (
	options?: RequestInit,
): Promise<getVatRateTypesResponse> => {
	return customFetch<getVatRateTypesResponse>(getGetVatRateTypesUrl(), {
		...options,
		method: "POST",
	});
};

export const getGetVatRateTypesMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getVatRateTypes>>,
		TError,
		void,
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getVatRateTypes>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["getVatRateTypes"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getVatRateTypes>>,
		void
	> = () => {
		return getVatRateTypes(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetVatRateTypesMutationResult = NonNullable<
	Awaited<ReturnType<typeof getVatRateTypes>>
>;

export type GetVatRateTypesMutationError = ApiErrorResponse;

export const useGetVatRateTypes = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getVatRateTypes>>,
			TError,
			void,
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getVatRateTypes>>,
	TError,
	void,
	TContext
> => {
	const mutationOptions = getGetVatRateTypesMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
export type getDocumentEntriesResponse200 = {
	data: DocumentEntryResponsePagedResult;
	status: 200;
};

export type getDocumentEntriesResponse400 = {
	data: ApiErrorResponse;
	status: 400;
};

export type getDocumentEntriesResponseSuccess =
	getDocumentEntriesResponse200 & {
		headers: Headers;
	};
export type getDocumentEntriesResponseError = getDocumentEntriesResponse400 & {
	headers: Headers;
};

export type getDocumentEntriesResponse =
	| getDocumentEntriesResponseSuccess
	| getDocumentEntriesResponseError;

export const getGetDocumentEntriesUrl = () => {
	return `/api/fincosts/costs/documents/list`;
};

export const getDocumentEntries = async (
	documentEntryListFilter: NonReadonly<DocumentEntryListFilter>,
	options?: RequestInit,
): Promise<getDocumentEntriesResponse> => {
	return customFetch<getDocumentEntriesResponse>(getGetDocumentEntriesUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(documentEntryListFilter),
	});
};

export const getGetDocumentEntriesMutationOptions = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof getDocumentEntries>>,
		TError,
		{ data: NonReadonly<DocumentEntryListFilter> },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof getDocumentEntries>>,
	TError,
	{ data: NonReadonly<DocumentEntryListFilter> },
	TContext
> => {
	const mutationKey = ["getDocumentEntries"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof getDocumentEntries>>,
		{ data: NonReadonly<DocumentEntryListFilter> }
	> = (props) => {
		const { data } = props ?? {};

		return getDocumentEntries(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GetDocumentEntriesMutationResult = NonNullable<
	Awaited<ReturnType<typeof getDocumentEntries>>
>;
export type GetDocumentEntriesMutationBody =
	NonReadonly<DocumentEntryListFilter>;
export type GetDocumentEntriesMutationError = ApiErrorResponse;

export const useGetDocumentEntries = <
	TError = ApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof getDocumentEntries>>,
			TError,
			{ data: NonReadonly<DocumentEntryListFilter> },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof getDocumentEntries>>,
	TError,
	{ data: NonReadonly<DocumentEntryListFilter> },
	TContext
> => {
	const mutationOptions = getGetDocumentEntriesMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
